### ISSUE TITLE
Read The Doc for Develop not accessible or wrong link on README

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring/alignak#1005]
Link inside README for develop doc link to:

http://alignak-doc.readthedocs.io/en/update/?badge=develop

But it seems, this link is not accessible.

**Comment by mohierf** [comment]
Strange ... this link: http://alignak-doc.readthedocs.io/en/develop/ is ok

**Comment by mohierf** [comment]
Fixed in python3 branch
