### ISSUE TITLE
No daemons folder in arbiter folder for v1.1.b tag

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring/alignak#1010]
If we try an installation on `v1.1.b`, the folder` daemons` in the folder `arbiter` has disappeared:

On `v1.1.b`, no folder:
https://github.com/Alignak-monitoring/alignak/tree/1.1b/etc/arbiter

And on `develop`, folder is here (and on other tags also):
https://github.com/Alignak-monitoring/alignak/tree/develop/etc/arbiter

**Comment by algorys** [comment]
Seems that all daemons cfg files have been moved to `alignak.ini` file.

**Comment by mohierf** [comment]
Indeed yes  ... all the daemon configuration is now in alignak.ini

Le mer. 28 mars 2018 à 14:37, Matthieu Estrada <notifications@github.com> a
écrit :
