### ISSUE TITLE
Implement true Alignak reload

### ISSUE THREAD

**Issue by aviau** [Alignak-monitoring/alignak#104]
I would like for Alignak-arbiter to reload (config) without changing PID.

**Comment by ddurieux** [comment]
What do you mean? reload is different than restart, so yes reload = no changing PID

**Comment by Seb-Solon** [comment]
Yes but actually the arbiter reload is usually done by init script . And the init script only implements restart. So yeah pid change, tehre is no signal handler to reload

**Comment by jremond** [comment]
alignak should handle SIGHUP as a reload signal
Would "alignak/daemon.py" manage_signal function be a good place to add it ?
I found a manage_signal function in schedulerdaemon.py too so should it be duplicated to arbiterdaemon.py instead ?

**Comment by Seb-Solon** [comment]
Yeah that basically where it hould be place @jremond . Instead of dumpy memeory or whatever you could set a flag like "need reload" and here we go.

**Comment by jremond** [comment]
Let's try !
https://github.com/Alignak-monitoring/alignak/pull/133
