### ISSUE TITLE
python psutils requirement

### ISSUE THREAD

**Issue by hvad** [Alignak-monitoring/alignak#1065]
Hi,

Python psutil need for alignak is 5.4.5 and in linux fedora version of python psutil is 5.4.3. There's a bug request (https://bugzilla.redhat.com/show_bug.cgi?id=1567102) to update python psutil on fedora 

Can you adjust version on fedora ? or put >= on requirement to accept version up to 5.4.5 ? 

Thanks

**Comment by mohierf** [comment]
Closed thanks to #1066
