### ISSUE TITLE
Add property hostgroup_members in Hostgroup class

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#110]
When comment modules (pylint), I have seen the function get_hostgroup_members of Hostgroup never works because property 'hostgroup_members' not exist.

So clean it and remove the call in function 'get_hosts_by_explosion' in same class

**Comment by mohierf** [comment]
Please do not remove ! This function is really useful for a Web UI ...

I made a PR in Shinken (https://github.com/naparuba/shinken/pull/1654) to add the missing property in the *hostgroup* and *servicegroupe* class !

**Comment by mohierf** [comment]
It is not possible to add this function in the module because the parsing of the configuration files is made elsewhere! 

Moreover I think that it is not a good idea to ignore standard Nagios object definition:
```
define hostgroup{
   hostgroup_name	hostgroup_name
   alias	alias
   members	hosts
   hostgroup_members	hostgroups
   notes	note_string 
   notes_url	url
   action_url	url
}
```

**Comment by ddurieux** [comment]
Ok, so it's the opposite, add hostgroup_members property in the class Hostgroup

**Comment by mohierf** [comment]
And *servicegroup_members* in the class Servicegroup ;-)

**Comment by gst** [comment]
any PR yet ? ;)

**Comment by mohierf** [comment]
Not yet in Alignak, but I proposed this PR in Shinken : https://github.com/naparuba/shinken/pull/1654

**Comment by gst** [comment]
ping ?
