### ISSUE TITLE
Host 'labels' property not right initialized

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#112]
In Host class, we have this property : 
```
        'labels':
            StringProp(default=[], fill_brok=['full_status'], merging='join', split_on_coma=True),
```

It's a string and default can't be [], or default is right [] but type is list, not string

**Comment by Seb-Solon** [comment]
Already mentioned in the road map, we have to clear also '' and None values

**Comment by ddurieux** [comment]
OK, but for this, labels is a list? (not sure but I think yes)

**Comment by Seb-Solon** [comment]
Well, it will be "die and retry" technique. Try to change and check tests status :)

**Comment by mohierf** [comment]
As of: http://shinken.readthedocs.org/en/latest/08_configobjects/host.html ... labels is a list !

**Comment by ddurieux** [comment]
I have read all properties of all objects, and we need to check all because many properties are not right

**Comment by gst** [comment]
> I have read all properties of all objects, and we need to check all because many properties are not right

what about doing that one property at a time, and each in its own PR ?
that'll be *a lot* easier than try to check/correct them all at the same time.. ;)

Who begins ? 
just create an issue & associated (empty for now) PR and whoever feels good about it will take over it.. after for some of them we can talk in each issue and/or PR ..
