### ISSUE TITLE
héritage de service entre model

### ISSUE THREAD

**Issue by hvad** [Alignak-monitoring/alignak#150]
Bonjour,

Lorsque que l'on attribue un template de service ping à un template d'hote generic-host et que l'on veut l' utiliser pour un autre template linux le service n'apparait jamais. 

Ma configuration pour exemple : 
define host{
        name                            generic-host
        alias                              generic-host
        check_command                   check_host_alive
        check_interval                  5
        max_check_attempts              3
        active_checks_enabled           1
        passive_checks_enabled          0
        check_period                    24x7
        contact_groups                  +Admin
        notification_period             24x7
        notification_options            d,r
        notification_interval           0
        realm                          All
        register                        0
}

define service{
        host_name                       generic-host
        name                            Ping
        service_description             Ping
        use                             generic-service
        check_command                   check_fping!3!3000,40%!5000,50%
        register                        0
}

define host{
        name                            Server-Linux
        alias                           Server-Linux
        use                             generic-host
        register                        0
        _SNMPCOMMUNITY                  $USER2$
}

Est ce que vous avez déjà eut le problème ? 

Merci

**Comment by hvad** [comment]
En fait il ne faut plus utiliser name dans la déclaration des objets sauf pour un seul template sinon cela ne fonctionne plus.

**Comment by gst** [comment]
c'est moyennement clair pour moi le problème..

**Comment by ddurieux** [comment]
ça pose soucis ça?

**Comment by mohierf** [comment]
@hvad still ongoing ?
