### ISSUE TITLE
Problem with trailing space in the description of a service

### ISSUE THREAD

**Issue by flaf** [Alignak-monitoring/alignak#177]
Hi,

Here is an example:

```
define host {
    host_name host-foo
    use       template-with-duplicate-foreach-key
    address   www.xxx.yyy.zzz

    # Key from a "duplicate_foreach" instruction.
    _my_key description n1 $(val1)$ $(val2)$, \
            description n2 $(val1)$ $(val2)$, \
            description n3 $(val1)$ $(val2)$,
}
```

In this example, the descriptions of the services will be `"description n1 "`, `"description n2 "` and `"description n3 "` with a trailing space in the name which will trigger some problems for instance in the WebUI. Indeed, the WebUI will have some dead links (error 500) such as `http://fqdn/service/<host>/<description-of-a-service>` (link to a service).

Currently, there is a workaround: just remove the space between the description and the dollar like this:

```
define host {
    host_name host-foo
    use       template-with-duplicate-foreach-key
    address   www.xxx.yyy.zzz

    # Key from a "duplicate_foreach" instruction.
    _my_key description n1$(val1)$ $(val2)$, \
            description n2$(val1)$ $(val2)$, \
            description n3$(val1)$ $(val2)$,
}
```
In this case, no problem, the descriptions will be `"description n1"`, `"description n2"` and `"description n3"`  without the trailing space.

But it should be smarter if the description of a service was systematically striped, ie with `desc = desc.strip()` somewhere in the code.

Regards.

**Comment by gst** [comment]
writing a test case triggering the problem should be rather easy..

gonna give it a try..

**Comment by gst** [comment]
Ok I could rather easily reproduce the problem in a test case.

**Comment by gst** [comment]
@flaf,

I've a fix ready but I'm not sure it's enough about your described problem (it does fix the testcase I've though),

from where come your $(val1)$ and $(val2)$  in your config extract ?

**Comment by gst** [comment]
> from where come your $(val1)$ and $(val2)$ in your config extract ?

said nothing, this is all from here : http://shinken.readthedocs.org/en/latest/08_configobjects/service.html 

"relevant" extract :
```
duplicate_foreach
This is used to generate serveral service with only one service declaration. Shinken understands this statement as : “Create a service for earch key in the variable”. Usually, this statement come with a “$KEY$” string in the service_description (to have a differente name) and in the check_command (you want also a different check) Moreover, one or several variables can be associated to each key. Then, values can be used in the service definition with $VALUE$ or $VALUEn$ macros.
define host {
  host_name    linux-server
  ...
  _partitions   var $(/var)$, root $(/)$
  _openvpns   vpn1 $(tun1)$$(10.8.0.1)$, vpn2 $(tun2)$$(192.168.3.254)$
  ...
}

define service{
       host_name               linux-server
       service_description     disk-$KEY$
       check_command           check_disk!$VALUE$
       ...
       duplicate_foreach       _partitions
}
```

I confirm I'm on a fix.. (it takes a bit longuer than my initial "easy" fix 'cause I'm going to rewrite most of the main functions involved in this "duplicate foreach" particular use case 'cause they're mostly bad (in their form and content).

**Comment by Seb-Solon** [comment]
If by any chance you still have no fix for that, you can have a look on Shinken side. It is supposed to be fixed. The fix is adding \s in regexp  basically.

**Comment by gst** [comment]
Seen that. But i'm doing more actually. Code smells, more problems than the one mentionned hère.

**Comment by Seb-Solon** [comment]
:+1:
