### ISSUE TITLE
Feature request : Implementd etcd support for all daemons

### ISSUE THREAD

**Issue by titilambert** [Alignak-monitoring/alignak#179]

**Comment by aviau** [comment]
Load config from etcd?

**Comment by gst** [comment]
their "*daemon*.ini" config I guess you mean @titilambert ?

**Comment by titilambert** [comment]
both daemon.ini and objects (hosts/services) config :)

**Comment by titilambert** [comment]
@aviau or maybe use etcd as backend instead of Mongo in Surveil ?

**Comment by ddurieux** [comment]
Not understand you want, it's not really clear, I close it, but if you want reopen it, say us ;)
