### ISSUE TITLE
Systemd ?

### ISSUE THREAD

**Issue by hvad** [Alignak-monitoring/alignak#180]
Hi,

I saw in file install_hooks.py this line :  

8 def get_init_scripts(config):
9     """ Add init scripts in data_files for install """
10     data_files = config['files']['data_files']
11     if 'win' in sys.platform:
12         pass
13     elif 'linux' in sys.platform or 'sunos5' in sys.platform:
14         data_files = data_files + "\netc/init.d = bin/init.d/*"  
15         data_files = data_files + "\netc/default = bin/default/alignak.in"

Can you add code to make it compatible with systemd ?

Thank

**Comment by gst** [comment]
>  I saw in file install_hooks.py this line :

..

>```
8 def get_init_scripts(config):
9 """ Add init scripts in data_files for install """
10 data_files = config['files']['data_files']
11 if 'win' in sys.platform:
12 pass
13 elif 'linux' in sys.platform or 'sunos5' in sys.platform:
14 data_files = data_files + "\netc/init.d = bin/init.d/*"
15 data_files = data_files + "\netc/default = bin/default/alignak.in"
```

okkk..  

> Can you add code to make it compatible with systemd ?

but what would be required ~~more exactly~~ actually ? 
if you know it : can you make a PR ? Thanks :)

**Comment by aviau** [comment]
The bug tag is wrong. Systemd is backwards compatible with sysvinit. This is an enhancement.

We should ship one .service file for all daemons.

I can review the PR when there is one.

**Comment by hvad** [comment]
Hi,

I think add line between line 14 and 15 in file install_hooks.py : 
         if 'fedora' in platform.dist()[0]:
             data_files = data_files + "\nsystemd/* = /usr/lib/systemd/system/*"   

But my goal, is to make rpm for fedora/epel. I think we must discussing packaging on irc or devel list. 

Regard

**Comment by mohierf** [comment]
@hvad: I just submitted a PR for setup scripts and I was not aware of this issue ... what about this? Are you still interested in this for Fedora?

**Comment by mohierf** [comment]
As explained by @hvad Alignak RPM is systemd compatible. I close this issue.

**Comment by Seb-Solon** [comment]
Well actually the RPM weekly built is not. I'll have to edit the spec. @hvad it a talking about the rpm he did on the side I think.

**Comment by mohierf** [comment]
Ok, so let's keep this open ...

**Comment by mohierf** [comment]
Closeing according to last packaging modifications
