### ISSUE TITLE
Documentation readthedoc

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#182]
We had discussions about it. 
We need to have an unique domain (readthedoc) for multiple types of documentations (on different repositories) like:
- user doc (repository https://github.com/Alignak-monitoring/alignak-doc)
- developper doc (repository https://github.com/Alignak-monitoring/alignak)
- alignak backend doc (repository https://github.com/Alignak-monitoring/alignak-backend)
- mod-alignakbackend doc (repository https://github.com/Alignak-monitoring/mod-alignakbackend)
- mod-surveil doc (repository ?)

We can do this like explained here: https://read-the-docs.readthedocs.org/en/latest/faq.html#how-do-i-host-multiple-projects-on-one-cname

We can have http://alignak.readthedocs.org/en/latest/ where centralize summary and each type of documentation listed before in link (example have http://alignak.readthedocs.org/projects/userdoc/en/latest/)

**Comment by gst** [comment]
about the docs : https://github.com/Alignak-monitoring/alignak-doc/issues/2

**Comment by ddurieux** [comment]
Yes but like I have put here, we will have many repository (many modules) and it can be good to 'merge' them in same place in an unique cname readthedoc

**Comment by mohierf** [comment]
@ddurieux should it be closed?

**Comment by ddurieux** [comment]
No, we must see if we can do this

**Comment by mohierf** [comment]
It may be the right time to take care of this, no ?

**Comment by mohierf** [comment]
Unique doc namespace on RTD ...

**Comment by ddurieux** [comment]
currently in construction, will be available with http://docs.alignak.net
