### ISSUE TITLE
remove android support

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#184]
I'd like to clean the project of any reference to android ; which is anyway not fully supported - if something would work at all..

any one wants to raise some cons about this ?

**Comment by ddurieux** [comment]
If not work, prefer delete it yes ;)

**Comment by gst** [comment]
> If not work, prefer delete it yes ;)

then we can delete most of the code :p

**Comment by Seb-Solon** [comment]
I would say +1. I guess this code was tested on old Android version (2.X). We are know on 6.X release. We could have a look at the python support but I guess the android python module have changed and so the import we use for android part.

**Comment by Seb-Solon** [comment]
Got my answer. Looks like it was using : https://github.com/damonkohler/sl4a to install python on android.
But : 
```
As of November 2014, it is incompatible with Android 5.0 (Lollipop) and it is not clear when or if this will be fixed
```
From Wikipedia.
