### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#217]
/home/travis/build/gst/alignak/test/test_svc_desc_duplicate_foreach.py:52: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  ctx.exception.message)

**Comment by gst** [comment]
also:

/home/travis/build/gst/alignak/test/test_properties.py:195: PendingDeprecationWarning: Please use assertEqual instead.
  self.assertEquals(p.pythonize(["1,2,3", "4,5,6"]), ["1","2","3", "4","5","6"])

**Comment by ddurieux** [comment]
Done in rewrite test_properties.py
