### ISSUE TITLE
Simplify (a lot) modules management

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#239]
The way the modules are managed isn't good at all. 

1) Actually every daemon load/import ALL the  available modules, even if none are actually used. This is simply bad.
2) there can be conflicts between different modules. More specifically with the "module_type" : 2 completely different modules could define the same module_type, the last one imported would take over the first one.
3) the code handling all that is, so, also bad, there are some duplications, etc..

I hereby propose to handle alignak modules like this : 

1) every module will need to be installed as a normal python module/package and so will be directly importable. At worst we could still play with PYTHONPATH for dev / test purpose. But we won't anymore hack with sys.path at runtime.

2) the module_type, defined in a `define module { .. }` section, will now be the name of the corresponding python module/package. So no more possibility of module_type conflicts.

3) the `properties` dict and the `get_instance` function will need to be available at the toplevel of each module.

That's it !

Ofcourse modules_manager will have to be adapted (quite deeply). and ~~probably~~ certainly others places which use that.

**Comment by gst** [comment]
See #240 for first implementation..

**Comment by Seb-Solon** [comment]
It's done right?

**Comment by mohierf** [comment]
As of what I saw, it is done ... I close this issue
