### ISSUE TITLE
passive check (nsca / PROCESS_SERVICE_CHECK_RESULT) have problem with perf_data 

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#243]
With a PROCESS_SERVICE_CHECK_RESULT (external command) from nsca, the perf_data is empty when arrive in broker.

With my investigations, seems ok when get the perf_data in function action.get_outputs but between this function and Brok('service_check_result') perf_data is lost

**Comment by Seb-Solon** [comment]
Any news about that? Was not able to reproduce with a mod-pipe. I had the perfdata printed in LS.

**Comment by ddurieux** [comment]
Ah? Will try with mod-pipe if I have same thing

**Comment by ddurieux** [comment]
Ok, works, it's a configuration problem with 'process_perf_data'
