### ISSUE TITLE
Question: Is it possible to monitor 30/50/more servers from a single installation of alignak + from web UI?

### ISSUE THREAD

**Issue by auvipy** [Alignak-monitoring/alignak#244]
need some doc for them to learn more.

**Comment by ddurieux** [comment]
The web UI (contribution) is not yet ready (but I think stable quickly, if @mohierf can confirm that).
For the number of servers to monitor, it depends on the resources of your alignak server but you can monitor 30/50/300/1000...

**Comment by auvipy** [comment]
well how powerful the master server need to be to monitor 50/100 dedicated servers from single pane?

**Comment by ddurieux** [comment]
Depends on checks you do on each server, but about 2 Go of RAM (4 is better) and 2 CPU for alignak + backend + webui
