### ISSUE TITLE
Single node Alignak installation

### ISSUE THREAD

**Issue by aftnix** [Alignak-monitoring/alignak#245]
Looking for a quickstart tutorial of single node alignak installation. The available documentation is somewhat unclear about all those myriad configuration files.

**Comment by ddurieux** [comment]
What part is not clear (link?) I will try to update it to be more clear with your information ;)

**Comment by aftnix** [comment]
https://alignak-doc.readthedocs.org/en/latest/03_how_it_work/high_availability.html

It uses 3 nodes. So if i use 1 node, it becomes a bit confusing. Say if i have only one node, I should not need to have a scheduler-slave.cfg , is that right?

And nothing is given about launching various daemon, (I think if it's properly configured, by just typing 'alignak-arbitar ' for example would do), but still some sample should have been given. Like some example scenarios with what kind of output is to be expected and how to see thing is running ok . For new users, this the most important thing. 

Also for people who neither has any experience of nagios or sheinken, but nevertheless want to start monitoring some servers rightaway, there should be technical introduction. Like what it does, in what way. How a particular node is monitored.

**Comment by Seb-Solon** [comment]
Hi,

If you have only one node then high availability is not necessary IMO. It's better to have spare in another server than the same one. So yeah in this case no slave file but of course, no high availability

Regarding daemon launching the usuage of each daemon could help you. But basically you will launch them like this

```
alignak-* -c CONFIG_FILE
```

Config file is alignak.cfg for the arbiter, the other are ini files

Another thing, package are on the way, it will provide more standard way to run daemon actually (systemctl, service etc..). This may help you a bit more

Last thing, consider using alignak user list : alignak@freelists.org ( user, registration http://www.freelists.org/list/alignak ) for such questions. Github is a bit more for bug, like the #246 you did. 

Thanks for using and the feedback.

**Comment by aftnix** [comment]
Thanks for the feedback. Well i know github issue isn't for this kind of queries, but the list archive showed no entries, so i thought list might be not be active. 

The problem was...Well I still don't understand(frankly) the what and how these daemon works. The documentation section for the daemons mostly list configuration options. But a high level overview would have been much welcome IMO. 

My use case is, I want to monitor handful of servers, for their uptimes, loads, log growth, disk usage, network usage etc. Right it means i have to run shell commands individually or using "ansible". The problem is by this way, i don't have any record of how my servers are functioning during a course of time, how the load changes from time to time, when it reaches the peak etc. I have no experience in nagios stuff, so I'm a little bit short of jargon to understand how my "shell commands" translate into a thing like alignak. 

Say, I want know how many http connections  are there in my webserver. currently i'm doing a 
```
sudo netstat -anp | grep :80 | grep ESTABLISHED | wc -l

```

How would i translate this into alignak?

A lot of things i have to monitor aren't that standardized stuff, that means there might not be batteries included (alignak) module for that, so running dirty commands is important at this moment.

**Comment by Seb-Solon** [comment]
I created a build for the old branch here : http://alignak-doc.readthedocs.org/en/old/
This is the version of the doc before we started to rewrite it. As the new is not finish you will be able to find more information on this one.

Alignak and the whole Nagios base family is a bit tricky, and it takes some times to discover and understand concept. I guess you are ready to learn in order to make it work the way you want.
The hint I can give you is to have a look at the concept of nagios-plugins (or monitoring-plugins), that's what you need to "translate" into alignak. The second tip I can give you is to use as much "packs" as possible. You can find a lot of resource amd example on github. For example : https://github.com/savoirfairelinux/monitoring-tools, https://github.com/shinken-monitoring?utf8=✓&query=Pack . Nagios-like community and contributions are time-saving resources.

**Comment by ddurieux** [comment]
I have added lines/commands to run alignak daemons: http://alignak-doc.readthedocs.org/en/latest/03_how_it_work/run_daemons.html
