### ISSUE TITLE
Default configuration notes and remarks

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#249]
Currently, in the default installed configuration: 
- it does not seem necessary to keep a template for a PNP4Nagios service (`templates/srv-pnp.cfg `)
- the default plugins directory defined in `arbiter_cfg/resource.d/paths.cfg` is not consistent with the configuration directories. It should be: `$PLUGINSDIR$=/usr/local/var/lib/alignak/libexec`
- the default time template (`time_templates.cfg`) are not defined correctly (property `normal_check_interval` is deprecated ...) and do not define time templates for hosts.
- the business impact templates are missing (eg. normal, important, ...)

**Note**: I will submit a PR with my proposals ...

**Comment by mohierf** [comment]
In `alignak.cfg`, there is still some configuration for the Shinken kernel.io ... I assume that it should be removed from default configuration.

```
# kernel.alignak.io communication channel. Create an account to http://shinken.io
# and look at your profile to fill this.
#api_key=
#secret=
# if you need an http proxy to exchange with kernel.alignak.io
#http_proxy=
```

**Comment by Seb-Solon** [comment]
1 . Easy of use for PNP user (legacy)
2 . I disagree to have a /usr/local/var/lib/alignak/libexec path. It's a non sense, alignak does not provide plugins anyway
3 . +1 
4. We could remove most of the time on and put a few example of business_impact ones.
5. +1

**Comment by mohierf** [comment]
1. if we include such service declaration, why not to do so for graphite? And why including those templates in the main templates directory? And why not in the packs directory?

2. Even if Alignak does not provide any plugins, it declares a directory where to search for the used plugins ... either we define one default directory, either we let each checks package declare its own directory ... why not? Let us make a choice and document this choice ...

4. it is easier to tag an host/service with keywords (eg. `important`, ....) rather then remembering that 3 is important, 2 is normal, ... let us keep this and if users do not want to use, they will not use.

**Comment by Seb-Solon** [comment]
1. Pack can be a good place to put them too. I have no opinion about it actually.
2. Default is the nagios-plugins one right? I don't see what we need to change. You would like another one?
3. I don't see how it is related to my previous comment. I agree to add the bp template, I was only suggesting to remove the some time template as they are using the old parameter.
 
We agree on most thing, waiting for your PR ;)

**Comment by mohierf** [comment]
Concerning the `$PLUGINSDIR$` macro defined in `arbiter_cfg/resource.d/paths.cfg`, it is used only in the default `notify-by-xmpp` commands present in the default configuration.

 It is easy to remove from the configuration. Clearly, it is not the monitoring framework to deal with the plugins installation/configuration ... as of it, each user may install and configure his monitoring plugins and then configure his commands properly.

 Ok, but ...

 I see some interests in defining a `$PLUGINSDIR$` macro: 
 - it is used in (almost ...) all the checks packs available on shinken.io
 - when installing some extra plugins for the checks, the user will need to copy them somewhere
 - and obviously, it must be a different location from the `$NAGIOSPLUGINSDIR$` ...

 I think that it is the monitoring framework that may propose this location to make easier the monitoring system configuration for the user. 

 Anyway, why defining some macros for Nagios, Windows, ... to prepare the checks installation and use, and why not defining something for other plugins.

 What do you think @ddurieux @Seb-Solon @gst ?

**Comment by ddurieux** [comment]
When I had checks manually (from nagios exchange for example), I add them in nagios folder

**Comment by mohierf** [comment]
During its installation, Alignak creates an `/etc/default/alignak` (or `/usr/local/etc/default/alignak` file), including this:
```
## These vars will override the hardcoded ones in init script ##
ETC=/usr/local/etc/alignak
VAR=/usr/local/var/lib/alignak
BIN=/usr/local/bin
RUN=/usr/local/var/run/alignak
LOG=/usr/local/var/log/alignak
```

We should add an extra path:
```
LIB=/usr/local/var/lib/alignak
```
which will be used to store the plugins installed by the packs.

**Comment by mohierf** [comment]
I propose to make the modification proposed in my last comment ...

**Comment by ddurieux** [comment]
+1
