### ISSUE TITLE
Default configuration and upgrade configuration proposal

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#253]
This issue to discuss what should be done for the monitoring objects configuration ...

### Introduction (currently)

Currently the default installed configuration is including:
- `etc/alignak/daemons`: alignak daemons configuration (*.ini)
- `etc/alignak/certs`: SSL certificates used for inter-daemons communication
- `etc/alignak/modules`: external modules configuration
- `etc/alignak/arbiter_cfg`: alignak "real" configuration
- `etc/alignak/arbiter_cfg/daemons`: alignak daemons configuration (*.cfg)
- `etc/alignak/arbiter_cfg/modules`: external modules configuration (again ...)
- `etc/alignak/arbiter_cfg/resource.d`: macro definitions for some plugins (Nagios, Windows WMI, ...)
- `etc/alignak/arbiter_cfg/objects`: monitoring objects configuration (hosts, services, contacts, ...)

This configuration declares: 
 - some basic templates for host/service/contact definition
 - one monitored host
 - default contacts (admin and user)
- default timeperiods
 - some commands for checks and notifications

 This basic starter configuration is based upon standard Nagios plugins and implies an `apt-get install nagios-plugins` to be able to run the default configuration. This only to check that localhost is alive ...

### Proposal for a simple default configuration

My proposal to-do list: 
- [ ] remove `etc/alignak/modules` and keep modules configuration into `àrbiter_cfg`
- [ ] remove `etc/alignak/arbiter_cfg/resource.d`
- [ ] build a simple configuration without nagios plugins installation

Once this made, the default configuration will be able to simply check that localhost is alive without needing to install nagios plugins.

### Proposal for future updates of the default configuration

To update the default configuration (add hosts, services, ...) I propose that we build some pip installable packages ... the main idea is to have something like `shinken install package` but based upon python `pip`.

We should manage each package in its own repository.

**Comment by ddurieux** [comment]
'remove etc/alignak/modules and keep modules configuration into arbiter_cfg' => it's in PR #240

So like we will have alignak_module_*, have alignak_config_* or alignak_template_*

**Comment by mohierf** [comment]
I do not understand your last proposal, what do you mean with: *So like we will have alignak_module_, have alignak_config_ or alignak_template_* ?

**Comment by ddurieux** [comment]
The name of packages in pip

Like we have: 
* alignak_module_nsca
* alignak_module_backend

**Comment by mohierf** [comment]
Ok. Yes

We should have: 
- `alignak_module_XXX` for a module
- `alignak_checks_XXX` for a checks configuration package

I am thinking about: 
- `alignak_checks_linux-snmp`
- `alignak_checks_linux-nrpe`
- `alignak_checks_windows-WMI`
- `alignak_checks_windows-nrpe`
- `alignak_checks_glances`

**Comment by ddurieux** [comment]
Ok for me for alignak_checks_* ;)

**Comment by mohierf** [comment]
See first checks packs in https://github.com/Alignak-monitoring-contrib
