### ISSUE TITLE
Alignak installation directory

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#254]
Whether Alignak is installation from distro's packages, from pip of from source code, is there any means to find out the main application paths (etc, lib, ...)?

When installed from source repository, everything seems to be installed in `/usr/local` ...

**Comment by Seb-Solon** [comment]
Yeah pip and setup.py should not write directly in system path such as /etc. packages are made for that. You have the install path in the installation log if you don't know where it is

**Comment by mohierf** [comment]
I found out that Alignak installs an `/usr/local/etc/default/alignak` or `/etc/default/alignak` file where all the path information are present:
```
## These vars will override the hardcoded ones in init script ##
ETC=/usr/local/etc/alignak
VAR=/usr/local/var/lib/alignak
BIN=/usr/local/bin
RUN=/usr/local/var/run/alignak
LOG=/usr/local/var/log/alignak
```

I used this file to get the default paths ...
