### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#255]
To enhance config + manage better module_checks_* packages, we need:
* update etc/alignak.cfg with patterns used to updated when install (like %(logdir)s)
* replace in etc/alignak.cfg 'cfg_dir=arbiter_cfg/resource.d' with '$PLUGINSDIR$=***' (*** is defined with os when install, like /var/lib/alignak or /usr/local/lib/alignak or /usr/lcoal/libexec/alignak)

**Comment by mohierf** [comment]
Linked with #249

**Comment by mohierf** [comment]
Indeed the setup.py script does not use any `%(logdir)` patterns. It simply replace the content of existing variables with the directory determined at installation ...

**Comment by mohierf** [comment]
I close this issue. The `$PLUGINSDIR$` variable is managed with #247
