### ISSUE TITLE
Reduce CPU on scheduler to replace macros

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#295]
In scheduler, each time it prepare a command, it replace macros.

But we can replace _static macros_ in arbiter (like macro $PLUGINSDIR$). With that, we can win some resources in scheduler ;)

**Comment by mohierf** [comment]
Hmmm.... many macros replaced by the scheduler are contextual running macros. This proposal is of no interest IMHO. Please re-open and argument if needed
