### ISSUE TITLE
Implement reload configuration without quit process

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#296]
It's in alignak.daemons.arbiterdaemon.Arbiter -> main()

in the main, we have:
  * set level debug
  * load_config_file
  * do_daemon_init_and_start
  * start external modules
  * hook_point('load_retention')
  * do_mainloop

so this is how change this after set level debug:

run a function named 'load_and_run()'
in this function :
  * save properties
  * load_config_file
  * do_daemon_init_and_start
  * start external modules
  * hook_point('load_retention')
  * do_mainloop
  * hook_point('save_retention')
  * stop external modules
  * stop daemons
  * restore all properties

when return, if reload config
  run again load_and_run()
else
  exit()

**Comment by mohierf** [comment]
What about this issue @ddurieux ?

**Comment by ddurieux** [comment]
it's done
