### ISSUE TITLE
cpickle vs simplejson

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#30]
I have seen many performances pages about thi son the web and we can see all result (cpickle > simplesjon and other cpickle < simplejson).

Somebody has made performances tests with both in alignak (currently use cpickle)?

If no, I can try it

**Comment by Seb-Solon** [comment]
well i you want to compare, try to compare the c version of json (usjon I thnk) I will be fair vs cPickle ;)

**Comment by ddurieux** [comment]
I have tested ujson and simplejson and we have problem because have objects in dict to serialize.

For example, I have in a dict
```
'contacts': <shinken.objects.contact.Contacts object at 0x808eaa6d0
```

So why not put in dict only data and the module use the object to assicate data with object. The good point for this is the data to serialize and size will be more small to pass between module via http/https.

**Comment by Seb-Solon** [comment]
We could start with define dumps and loads function for every item (in Item?) so that we can call json on it

**Comment by ddurieux** [comment]
cpickle removed to json in #294
