### ISSUE TITLE
No notification when a service is NOK while the host is down in `soft` state type

### ISSUE THREAD

**Issue by flaf** [Alignak-monitoring/alignak#307]
Be careful, behavior seen with Shinken. Here is the timing:

- service `srv-1/foo` is NOK in state type `soft`
- check of the host `srv-1` DOWN in state type `soft` (1)
- service `srv-1/foo` is NOK in state type `hard` (2)
- check of the host `srv-1` UP
- service `srv-1/foo` stays NOK in state type `hard`...

(1) No notification but it's normal because the state type is `soft`.
(2) No notification probably because the host is DOWN but it's a `soft` DOWN so it's not normal.

Conclusion: the service `srv-1/foo` stays NOK but there is absolutely **no notification**.

**Comment by ddurieux** [comment]
Need rewrite part of schedulingitem.consume_results

**Comment by mohierf** [comment]
Fixed with #452
