### ISSUE TITLE
somewhen later:  remove back-compatibility import trick/hook used for modules 

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#31]
https://github.com/Alignak-monitoring/alignak/pull/27  was required to have modules still working with us.

Once we will have stabilized/cleaned the modules loading (so we'll have to fork each module we want to use/keep and replace import shinken by import alignak, probably also cleaning them by the way) : 
remove the hook we added in #27 .

**Comment by ddurieux** [comment]
So remove _shinken_import_hook_
