### ISSUE TITLE
Active / passive monitoring

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#315]
Host / services checks may be: 

- active only
- passive only
- both active and passive

When active checks mode is enabled, the host state is set according to the host check command result and the host services checks are launched according to this state. Ok, but what about passive checks...

When active **and** passive checks are enabled for an host or service, we assume that the active check process is taking place and we have the same behavior...

When **only passive checks** are enabled, the environment is not the same at all because no more checks are launched by Alignak ... as of it:

- the check commands are launched when the freshness period expires. Indeed, they are not *check commands* but freshness expiry notification commands ...
- the services / host dependency relation should be considered to ignore service freshness expiry when an host freshness period has expired

Rather than launching the check commands, Alignak should consider that a service has an `UNKNOWN` state when the freshness period expires. The same state should be used for an host when no host check has been received within the freshness period threshold.

Ok, the meaning of `UNKNOWN` is not exactly the best we should expect ... but creating a new specific state for the lack of information is probably not that easy. In stead, we should define an Alignak configuration parameter on the same model as `initial_state`: `host_freshness_state` and `service_freshness_state` ?

And ok also. It should be better to launch a command and the let the admin do what he wants ... if necessary, we should then define a new `host_freshness_command` and `service_freshness_command` ... but I am not sure that this would be necessary. If a command needs to be launched for passive host/service, event handlers may be used...

 Managing the dependency between services and their host should also be different than the standard active checks process ... when a passively checked service is `WARNING` or `CRITICAL` we should not care about the host state.

**Comment by ddurieux** [comment]
We can have the property on host and service definition, so name it _freshness_state_.
For the freshness_command, we can use event_handler, I think it's enough

**Comment by mohierf** [comment]
Adding a `freshness_state` property on each host/service is a bit heavy ... why not adding only one parameter in *alignak.cfg* like the `initial_state`?

**Comment by ddurieux** [comment]
it's like initial_state, default is CRITICAL / DOWN and you can modify it in each host / service. If required, you can modify it in templates because perhaps you don't want the same definition everywhere ;)

**Comment by mohierf** [comment]
Ok, but what about the `initial_state` defined in alignak.cfg ???

**Comment by ddurieux** [comment]
there is no _initial_state_ in general configuration :p

**Comment by mohierf** [comment]
As a sum-up:

- [ ] add a `freshness_state` for hosts and services. Default value is `DOWN` for an host and `UNKNOWN` for a service

- [ ] on freshness period expiry, set host/service state to its defined ` freshness_state` and set its `output` in the livestate to `Freshness period expired`

- [ ] for passively check host/service, do not launch a check on scheduler start when stale state is detected, but let the freshness period run ...

**Comment by Seb-Solon** [comment]
Ok. I've just jumped in the issue. 

>    add a freshness_state for hosts and services. Default value is DOWN for an host and UNKNOWN for a service

 >  on freshness period expiry, set host/service state to its defined freshness_state and set its output in the livestate to Freshness period expired

Isn't this acheivable by setting the check_command of this service/host as check_dummy!STATE!OUTPUT? I know that there are some plugin that just return the state youwant with the output wanted. I agree that it may be a workaround and you may want to use the check_command for a real active check when necessary. Unless you were planning to use event handler? Those are the same for passive check in my opinion

  > for passively check host/service, do not launch a check on scheduler start when stale state is detected, but let the freshness period run ...

+1 for this one, I am pretty sure it is never a good idea to schedule a forced-check at start time for a passive check

**Comment by Seb-Solon** [comment]
Lgtm
