### ISSUE TITLE
Default receiver configuration

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#316]
The receiver default configuration is:
```
direct_routing      0
```

This makes the receiver not sending the external commands that it builds from NSCA packets to its scheduler ... and thus the checks are not considered by Alignak.

The `direct_routing` parameter should be set to 1 !

**Comment by Seb-Solon** [comment]
The packets are sent however, but to the arbiter. The arbiter sends them to the scheduler afterwards. It's not a big deal when you have only a few passive check but can be bad in large env

**Comment by mohierf** [comment]
Currently, if you do not set the direct routing in the receiver, the received passive checks are not considered by Alignak ... so there is something missing somewhere :wink:

**Comment by Seb-Solon** [comment]
yup, we need to dig on why the arbiter is not getting external commands. This is the true bug here.

Do you have any logs for that? Do you see any http get traffic from the arbiter to the receiver  on get_external_commands?

Maybe there is serialization issue here : https://github.com/Alignak-monitoring/alignak/blob/3067040acce0557178db6b6fb5b3f9e5c5394b8b/alignak/objects/satellitelink.py#L464

**Comment by mohierf** [comment]
I will try to have a look and provide some logs ...

**Comment by ddurieux** [comment]
Perhaps we can send the realm conf + scheduler urls to the receiver (like for scheduler) and when receive an nsca or other, search in conf the realm assciated to host or service and send directly to scheduler
