### ISSUE TITLE
Default dependency_period should be 24x7 if not specified

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#320]
As explained in https://github.com/Alignak-monitoring-contrib/alignak-backend-import/issues/21, Alignak should set a default 24x7 timeperiod for an hostdependency `dependency_period` if it not set in the configuration file.

Doc: https://alignak-doc.readthedocs.io/en/old/08_configobjects/hostdependency.html
**the dependency is considered to be valid during all times.**

**Comment by mohierf** [comment]
To be confirmed with #440

**Comment by ddurieux** [comment]
In Nagios and here, not use this property = all time

**Comment by mohierf** [comment]
Add a test for timeperiods in the dependencies tests
