### ISSUE TITLE
error SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#322]
With SSL, have problems, like 

```
Python httplib SSL23_GET_SERVER_HELLO:unknown protocol
```

See this post http://stackoverflow.com/questions/18669457/python-httplib-ssl23-get-server-hellounknown-protocol

**Comment by Seb-Solon** [comment]
Ok actually the issue is with request no httplib.

Here is a link to implement it correctly : https://lukasa.co.uk/2013/01/Choosing_SSL_Version_In_Requests/

**Comment by Seb-Solon** [comment]
Actually it was linked to the CherryPy version. We have to update the requirement. Poke spea on IRC for that

**Comment by ddurieux** [comment]
the new SSL code works with pyOpenSSL >= 0.15 , so think its 'ok
