### ISSUE TITLE
Configuration warning for missing contacts

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#325]
When loading a configuration where some hosts only have a `contact_groups` property without defined `contacts`, Alignak logs a Warning: **[Alignak] [host::ek3022fdj-00006] no contacts nor contact_groups property**

This log should not be present because the `contact_groups` is defined and exists in the configuration

**Comment by mohierf** [comment]
To be confirmed

**Comment by ddurieux** [comment]
Seems fixed since the issue opened
