### ISSUE TITLE
Delete files

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#326]
Delete:
* misc/datamanager.py
* db.py
* db_*.py

**Comment by mohierf** [comment]
Should also delete the Regenerator class. This class is never instanciated in Alignak. It was formely used in Shinken for modules like the LiveStatus or the WebUI ...

**Comment by mohierf** [comment]
We should also delete the sorter.py file that contains also functions which are not used anymore. Thos functions where used in the DataManager or in the WebUI.

Same for the filter.py file ...
