### ISSUE TITLE
useful/unuseful shell scripts in bin directory ?

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#336]
The *bin* directory has many scripts to start or staop alignak daemons. Currently those scripts are not running correctly ...

What should be done whit this ?

IMHO, removing those scripts may be interesting ...

**Comment by ddurieux** [comment]
+1

**Comment by mohierf** [comment]
Ok, I remove them ...

**Comment by Seb-Solon** [comment]
They are use for develop purposes.

**Comment by mohierf** [comment]
@ddurieux +1, @Seb-Solon -1: I do what I want so ... :wink: 

Ok. I will restore them ... if it may help. But should add this in the documentation: @ddurieux

**Comment by Seb-Solon** [comment]
No actually it was more to mention the usage. I personally only use the launch / stop all when a need to debug a specific daemon for example. I do a launch all and then kill / manually start one daemon. 

Maybe they fit better somewhere else. I don't have a strong opinion on it

**Comment by mohierf** [comment]
What about moving those scripts in a dev directory where we should store all the dev stuff ? Thus, the bin directory will remain only for setup / packaging ... it seems more clear like this :wink:

**Comment by mohierf** [comment]
Followinf the last commit, I will update doc to explain ...

**Comment by mohierf** [comment]
I added my own start / stop scripts that use the `screen` utility ...

**Comment by mohierf** [comment]
Doc updated in https://github.com/Alignak-monitoring/alignak-doc/pull/9
