### ISSUE TITLE
Auto-generated modules: remove and create real python modules

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#338]
Currently, if some parameters are defined in the configuration, Alignak creates some auto-generated modules. Those modules are mainly to keep compatibility with some Nagios parameters: 

Moreover, the new Alignak module manager implementation makes that those modules are not known in the corresponding daemons :disappointed:  One more point to be in favour of suppressing this feature ...
```
        # Alignak arbiter modules
            # command_file parameter
            "NamedPipe-Autogenerated",

        # Broker modules 
            # status_file
            "Status-Dat-Autogenerated",

            # log_file
            "Simple-log-Autogenerated",

            # use_syslog
            "Syslog-Autogenerated",

            # service_perfdata_file
            "Service-Perfdata-Autogenerated",

            # host_perfdata_file
            "Host-Perfdata-Autogenerated",

        # Scheduler modules 
            # state_retention_file
            "Nagios-Retention-File-Autogenerated",
```

**Comment by mohierf** [comment]
I tag the source code with some TODOs

**Comment by ddurieux** [comment]
Remove them and create real modules

**Comment by mohierf** [comment]
We will create real modules on need ... we could check those of interest

**Arbiter modules:**
- [ ] NamedPipe, to get external commands

**Broker modules:**
- [ ] Status-Dat, of no interest, old Nagios parameter
- [ ] Simple-log, may be of interest
- [ ] Syslog, may be of interest
- [ ] Service-Perfdata, of no interest, old Nagios parameter and backend has a perfdata module
- [ ] Host-Perfdata, of no interest, old Nagios parameter and backend has a perfdata module

**Scheduler modules :**
- [ ] Nagios-Retention-File, of no interest, old Nagios parameter and backend has a retention module

**Comment by mohierf** [comment]
Indeed what makes the configuration parser is simply to declare those modules ... the logs are only present to alert the user that if he wants those parameters he should add the real modules on its installation!
