### ISSUE TITLE
Modify scheduler_loop function in AlignakTest

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#341]
We need to modify the function _scheduler_loop_ to work more with reality of alignak behavior

When define for a host a result, not create a check, but get the check planned, push the result in it.

[scheduler_loop.txt](https://github.com/Alignak-monitoring/alignak/files/476366/scheduler_loop.txt)

**Comment by Seb-Solon** [comment]
This issue is not very clear IMO

**Comment by ddurieux** [comment]
Actually, we create check when want add to scheduler, but the real behavior in scheduler is to create check, and receive (from poller) the check + result inside.

The goal of this modification if to get the check, put result inside and manage the result in scheduler

**Comment by ddurieux** [comment]
Done ;)
