### ISSUE TITLE
Arbiter default realm name if no realm exists

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#345]
When no realm exist in the configuration loaded by the Arbiter, the Arbiter creates a default realm named as `Default`. Every where in the configuration, the Arbiter satellites are configured to use a realm named `All` ... it would be much more logical that the default created realm be named as `All` and not `Default` ...

**Comment by ddurieux** [comment]
I agree

**Comment by Seb-Solon** [comment]
Make sense. It works at the moment because internally we get the default realm by checking the is_default attribute not the name
