### ISSUE TITLE
setup.py should not replace modified configuration files

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#349]
Actually, the python setup script replaces all the existing configuration files whatever they were modified or not. It may be interesting to find a solution to avoid deleting the configuration files. I see several solutions:
- [ ] default behavior should be to create the files but **not** replace existing files and to add a setup parameter that will force replacement
- [ ] on installation script end, create a local file that contains the installation date and, on installation script start, check if existing files have been modified since the installation date before replacing them
- [ ] create an _etc/alignak.backup-YYYY-MM-AA_ directory to save the existing files before replacing them

In any case, the script will indicate on the console if some files have been replaced

**Comment by mohierf** [comment]
:+1: for the third solution

**Comment by mohierf** [comment]
Why not using the [alignak-setup library](https://github.com/Alignak-monitoring-contrib/alignak-setup) that is used for the modules and checks packs?

**Comment by algorys** [comment]
I noticed that:

- Files inside /usr/local/var/libexec/alignak are removed also
- modules files also. To reinstall modules files, I've to pip uninstall before and pip install <alignak_module> again :cry: 

Maybe prevent user before install should be first step ? Like that, waiting a good solution, user can cancel installation and backup his file before.

**Comment by mohierf** [comment]
Close this issue. All configuration distribution is discussed in #723
