### ISSUE TITLE
Macro expansion in custom variables fail

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#350]
Assuming this configuration: 
```
#-- Default SNMP community
$SNMPCOMMUNITYREAD$=public

define host {
    name                linux-snmp
    use                 generic-host
    register            0

    _SNMPCOMMUNITY      $SNMPCOMMUNITYREAD$
    _SNMP_MSG_MAX_SIZE  65535

```

I expect to have an `_HOST_SNMPCOMMUNITY` variable that is evaluated to **'public** as declared in the `$SNMPCOMMUNITYREAD$` macro ... but the custom variable is evaluated to the string `$SNMPCOMMUNITYREAD$` instead of the string `public`

**Comment by Seb-Solon** [comment]
I think this one is legit. I remember to use this fpr AD auth. See : https://github.com/savoirfairelinux/pack-windows-sophos-mssql/blob/master/pack/templates.cfg

**Comment by mohierf** [comment]
To be confirmed
