### ISSUE TITLE
WARNING for duplicate service with host template

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#368]
When declaring a service attached to an host template, Alignak logs WARNING message that should be avoided

```
[1474891665] WARNING: [Alignak] [service::Disque] duplicate service name (u'host', u'Disque') in /home/alignak/conf_/host.cfg:45, using lastly defined. You may manually set the definition_order parameter to avoid this message.
```

**Comment by Seb-Solon** [comment]
The warning is that you have defined twice a service "Disque" on the host "host"

**Comment by mohierf** [comment]
Not always ... it seems that simply defining a service attached to a template if you do not have an host inheriting from this template also logs this warning ... to be confirmed with more tests. I keep this open to not forget ...

**Comment by mohierf** [comment]
The problem is with this configuration: A template based upon another template. 

All the services of the host defined on the inherited template raise a WARNING message during the configuration parsing ... but it should not !

```
define host {
    name						        windows-nsca-host
    use            				        generic-host
    register       				        0
}
```

```
define host {
    name						        north-host
    use            				        windows-nsca-host
    register       				        0
}
```

```
define host{
    use                     north-host
    host_name               passive-01
    alias                   Passive host 1
    address                 0.0.0.0
}
```

**Comment by mohierf** [comment]
Fixed
