### ISSUE TITLE
AUTHORS file update on setup.py

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#370]
When the *setup.py* script runs, it updates the AUTHORS file because of `pbr` ... we must choose if this file should be updated thanks to pbr or not ... 

The same problem exists with the `ChangeLog` file built by pbr ... we already have a `Changelog` (lowercase L) file ...

**Comment by mohierf** [comment]
Because this modification is really easy, we should do it. I propose to:
- rename the current AUTHORS files as AUTHORS.md,
- rename the current Changelog file as Changelog.md,
- include the two pbr files in the .gitignore (AUTHORS and Changelog)

As of it there will be no confusion with the `pbr` generated files ... and this will avoid mistakes with commits :wink: 

@Seb-Solon, @ddurieux : please vote for this

**Comment by Seb-Solon** [comment]
https://github.com/openstack-dev/pbr/blob/64699d79bec5f0955566aa9129a6b9dbf686035f/doc/source/packagers.rst

```
br generates AUTHORS and ChangeLog files from git information. This can cause problem in distro packaging if package maintainer is using git repository for packaging source. If that is the case setting SKIP_GENERATE_AUTHORS

SKIP_GENERATE_AUTHORS=1

will cause logic around generating AUTHORS using git information to be skipped. Similarly setting SKIP_WRITE_GIT_CHANGELOG

SKIP_WRITE_GIT_CHANGELOG=1

will cause logic around generating ChangeLog file using git information to be skipped.
```

Does that fit your need?

**Comment by mohierf** [comment]
Yes it does ...

**Comment by mohierf** [comment]
As discussed, we should define these environment variables in the setup.py script if they do not exist. @ddurieux ?
