### ISSUE TITLE
Avoid mutable as default value in Property item (Listprop)

### ISSUE THREAD

**Issue by Seb-Solon** [Alignak-monitoring/alignak#403]
It is a well know python issue : 

however we stil ahve some default to [].

This will cause isse like the following :  https://stackoverflow.com/questions/1132941/least-astonishment-in-python-the-mutable-default-argument, http://docs.python-guide.org/en/latest/writing/gotchas/

```
from alignak.objects.realm import Realm
r1 = Realm()
r1.fill_default()

In [8]: r1.realm_members
Out[8]: []

r2 = Realm()
r2.fill_default()
In [12]: r2.realm_members
Out[12]: []

r2.realm_members.append("JIJI")

In [14]: r2.realm_members
Out[14]: ['JIJI']

In [15]: r1.realm_members
Out[15]: ['JIJI']

```

**Comment by mohierf** [comment]
Currently there are quite a lot of ListProp that are declared as default [] ... 

IMHO I think that we should remove the `properties` dict in the objects and use real Python attributes ... the main benefit would be to have a more Python friendly source code ... we should use a dedicated prefix  for those attributes, eg. `_a_host_name`, `_a_serfice_description`, ...

**Comment by mohierf** [comment]
Related with #442

**Comment by mohierf** [comment]
Keep using the Alignak Prop based classes. Checked that only the ListProp attributes have an [] default value
