### ISSUE TITLE
Nagios log implementation

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#410]
As proposed in #262, we intended to rework this part.

Currently the NAGIOS log function (`naglog_result`) is using an awful hack to change and restore *on-the-fly* the log formatters of the main Alignak logger ... I propose to add an extra logger for the NAGIOS logs.

**Comment by mohierf** [comment]
**Preamble:**
Indeed, what we call NAGIOS log is information about the monitoring activity:
- ALERT
- NOTIFICATION,
- EXTERNAL COMMAND
- ...

Those logs are **THE** information that the Alignak user expects to get. We may say that they are the application log. All other daemon logs are the internal Alignak activity logs ...

As of it, I propose to build a specific file for the NAGIOS logs:
- easier for the end-user (pre-filtering)
- easier for parsing with tools like LogStash

Building this file may be done:

1. with specific broks handled by a broker module
   - *pros*: do not include specific alignak code for this feature
   - *cons*: make available broks to whoever wants to do something with

1. with a specific logger based upon the current Log class
   - *pros*: simple solution, replace *naglog_result call* with *logger_nagios.info*
   - *cons*: no broks available for extension module

Note that the two solutions are compatible and we may, short term, have a dedicated logger, middle term, implement new broks for extending alignak.

@ddurieux @Seb-Solon : what do you think about this?

**Comment by mohierf** [comment]
After more brainstorming and discussion about this:
- the so-called NAGIOS log are indeed the main Alignak provided information to the end-user
- we should rename this as **Alignak log** (any other idea ?)
- having a separate log file for the Alignak log is a nice idea
- on a single node installation, no problem to have a single file built with Python logger, but what is it for on a distributed installation?

**Comment by Seb-Solon** [comment]
Nagios log are monitoring logs actually. Alignak logs are logs generated by the application but not related to monitoring.

I would suggest to replace the Nagios logs by broks and then export those broks into a file if necessary. Doing this is as complicated as having another logger. Here we replace all naglog_result call by something like self.broks.append(Brok({..})).

Broks will be collected by sheduler every loop and sent to a broker. Another way to do it would consist in returning the brok directly so that the scheduler handles it but it is a bit more complex

**Comment by mohierf** [comment]
As I discussed with @ddurieux this morning, what we call "Nagios log" is indeed what is interesting the Alignak user and what I called **Alignak log**. The other logs are made to track Alignak framework activity ... and, as an end-user monitoring a system, I do not car about them as soon as I do not have any problem.

Having a broker module deal with the **Alignak log** do not allow to have a centralized log file in a distributed environment. Each broker of each realm will have its own log file. Or did I missed something?

**Comment by Seb-Solon** [comment]
You always have a scheduler associated to a broker. So if you have several broker logging those event, you will also have several sched. Unless you duplicate some information. Sending everything to the broker only helps for exporting

**Comment by mohierf** [comment]
What about my previous comment suggestion:

> Making a central point for the Alignak logs in the Arbiter daemon seems the best solution to achieve this. The Arbiter may catch a specific type of brok (eg. `alignak_log`) to create a log with a dedicated logger.

**Comment by Seb-Solon** [comment]
Having the arbiter to centralize log require a way to send logs to the arbiter. It is pretty much the same as the sending broks right?

**Comment by mohierf** [comment]
Yes. The `naglog_result` function should be replaced with a dedicated brok ... as I proposed.

**Comment by mohierf** [comment]
My last tests:
- create a `application_log` type Brok in the `naglog_result` function and return this brok
- the returned brok is added to the owner daemon broks
- in the scheduler, get the arbiter configuration in the dispatched configuration
- in the scheduler, create an HTTP connection with  the Arbiter and push the `application_log` broks to the arbiter
- added a `push_application_logs` method in the arbiter interface
- in the arbiter, the `application_log` broks message contained in the date is logged in a dedicated logger

**Comment by mohierf** [comment]
Most recent decision:
- add a broker module to catch the `monitoring_log` broks
- this broker module builds a monitoring log file

Updated the previous comment according to this decision.

**Comment by mohierf** [comment]
Tha Alignak Logs module allows to catch the monitoring logs to build a rotating file log: https://github.com/Alignak-monitoring-contrib/alignak-module-log
