### ISSUE TITLE
Make a clear status on realm daemons

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#415]
My current testing configuration is as follow:
- some hosts in the All realm
- some hosts in a North realm, member of All realm

With this configuration installed on a single server I am obliged to run a scheduler, a broker, a poller and a receiver for each realm.

Does it seem ok to all: @ddurieux @Seb-Solon

**Comment by mohierf** [comment]
Any answer about this: @ddurieux @Seb-Solon ?

**Comment by ddurieux** [comment]
With multi-broker pr merged, you need a scheduler for each realm, but you can have a broker, poller and receiver in Realm All + manage_sub_realms to 1

**Comment by mohierf** [comment]
To be tested ...
