### ISSUE TITLE
Configuration with realms and poller that manage sub-realms

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#422]
Let's assume a realm configuration with a main _All_ realm with one or more sub-realms

The poller declared in the realm _All_ can `manage_sub_realms`. As of it, it should not be necessary to declare a poller attached to the sub-realms ...

Currently, if the sub-realms do not have their own poller, the configuration is considered as invalid by the Arbiter when it is parsed.

A configuration error is raised:

```
Configuration errors:
 - Error: Hosts exist in the realm <Realm "name"=u'realm3' /> but no poller in this realm
 - Error: Hosts exist in the realm <Realm "name"=u'realm2' /> but no poller in this realm
```

**Comment by ddurieux** [comment]
oh, yep it's not good ;)

**Comment by mohierf** [comment]
This is why we are currently obliged to have one poller per realm ...

**Comment by mohierf** [comment]
Linked to #415
