### ISSUE TITLE
Dispatcher tries to send configuration to missing satellites

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#428]
The dispatcher tries to send the configuration to the missing satellites and it is raising some errors...

It would be better, when some missing satellites are detected, to only alert about the missing satellites and to not try sending the configuration until the missing satellites are back... 

Periodically checking that the satellites are up will allow to send the configuration (if not yet sent...) to the up satellites.

**Comment by mohierf** [comment]
@ddurieux : what about this?

**Comment by Seb-Solon** [comment]
From what I remember, dipatching and satelling ping are coupled. We used to update the satellite state while trying to send conf. With the new dispatcher it may be different so that we can have 2 separated logics

**Comment by mohierf** [comment]
Do not send configuration to satellite that are not alive.

**Comment by Seb-Solon** [comment]
Related to #664

**Comment by mohierf** [comment]
Currently we often have dispatching errors on arbiter start ... it seems that the dispatched configuration is not confirmed by the daemons. @ddurieux this is what we discussed recently!

I will copy some log as soon as I catch them on a next restart

**Comment by ddurieux** [comment]
need rewrite how dispatcher manage satellites

**Comment by mohierf** [comment]
#819 manage this potential problem
