### ISSUE TITLE
Arbiter receiving SIGHUP signal does not reload but exits ...

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#430]
When the Arbiter receives a SIGHUP signak, it should reload its configuration but rather than reloading it exits ...

The `alignak` script used for init.d uses the SIGHUP signal to make Arbiter reload its configuration ...

**Where is the truth?**

**Comment by mohierf** [comment]
Receiving a `SIGHUP` in any daemon makes it set its `need_config_reload` attribute to True, but the Arbiter hasa special treatment for this signak introduced with this PR: https://github.com/Alignak-monitoring/alignak/pull/412

@ddurieux : wht do you think about it?

**Comment by ddurieux** [comment]
Seems Linux specific, so perhaps add a new property in arbiterd.ini to bypass the internal reload

**Comment by Seb-Solon** [comment]
You may find the answer in previous issue. there are some standard for signal meaning, I can't remember what is it common to do with SIGHUP

**Comment by mohierf** [comment]
It is now ok. Verified on FreeBSD with `kill -s HUP 77004` ... the Arbiter process is not killed and the Arbiter reload its configuration. :+1:
