### ISSUE TITLE
broker, queue, external module crash ans memory leak

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#47]
Broker put data to queue for each external modules.
When a module crash, it restart the module external with new queue but old queue not deleted and is always in memory of broker process.

**Comment by gst** [comment]
hmm.. normally the old queue should be garbage collected as, if I'm not wrong, it will lose all references to it.. (well it *should*).. to be double-checked..

**Comment by mohierf** [comment]
It seems that unused queues are deleted (class ModulesManager, def remove_instance) ...
