### ISSUE TITLE
Monitoring logs classification

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#472]
Raised monitoring logs are:
 - TIMEPERIOD TRANSITION

 - EXTERNAL COMMAND

 - PASSIVE HOST CHECK
 - PASSIVE SERVICE CHECK

 - HOST ALERT
 - CURRENT HOST STATE
 - HOST NOTIFICATION
 - HOST EVENT HANDLER
 - HOST SNAPSHOT
 - HOST FLAPPING ALERT (STARTED / STOPPED)
 - HOST DOWNTIME ALERT (STARTED / STOPPED / CANCELLED)

 - same for SERVICE as for HOST.

 - RESTART PROGRAM
 - RELOAD PROGRAM

All those logs raise a `monitoring_log` brok which has an associated `level`. Most of logs have a **critical** level ... which is not really appropriate.

**Comment by mohierf** [comment]
What I propose:

 - the default `level` is **info**, except for the following

 - host/service check monitoring log is **error** for a not OK state

**Comment by Seb-Solon** [comment]
Based on what an event is more "important" than another? I don't really get the use of level actually. Unless we use it to prioritize something (like check for a type of event more often than another one?) ?

**Comment by mohierf** [comment]
I do agree with you. The event level is only present because it existed in the former Nagios log. If i developed from scratch I should have not kept this information, but:

 - As default, the logs module builds a log file where each log has its level included but you may configure to only have a date and an event.
 - It may be interesting to tail on this log file and grep only the ERROR logs
 - you may set a logger to ignore INFO and forward ERROR to the syslog
 - ...
