### ISSUE TITLE
Notifications for unreachable

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#481]
With two hosts, like in the default tests configuration, where **test_router_0** is a parent of **test_host_0. On both hosts: `notification_options d,u,r,f,s`, and on the attached contact `host_notification_options d,u,r,f,s`.

When both hosts go down, we get the "DOWN" notification for **test_router_0 and nothing for **test_host_0**. What is expected is to have an UNREACHABLE notification for **test_host_0** ...

The hosts are in the expected states: **test_router_0** is DOWN and **test_host_0** is UNREACHABLE.

Is it a problem dur to the current dependencies being faulty ... not sure. To be checked with more tests ...

**Comment by Seb-Solon** [comment]
What is expect is to have the minimum of notification to help you detect the root cause. So no you won't get a notification for unreachable as a parent is down. Otherwise you will have n notification for all son of a dead router, and it can be huge.

**Comment by mohierf** [comment]
In understand your position but what I expect is to have those notifications because I configured my notification as  `notification_options d,u,r,f,s` which means that I want all the notifications for this host, even the UNREACHABLE ones ...

**Comment by mohierf** [comment]
To be tested with new dependency management

**Comment by ddurieux** [comment]
The notification depend on _notification_failure_criteria_ defined in hostdependency first, if this will send notification, alignak see _notification_options_ of the host to know if send a notification and at the send see the contact notification options :)
