### ISSUE TITLE
Module parameters name must not overload some alignak attributes

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#504]
When a module defines its parameter, one must take care that some attribute names are not fully usable. as an example: 

```
define module {
    module_alias            web-services
    module_types            web-services
    python_name             alignak_module_ws

   ... 

    #-- Network configuration
    # Interface the modules listens to
    #host                    0.0.0.0
    #port                    8888
}
```

The `port` parameter (that is not defined...) will be overloaded with  the Alignak daemon port value that is set to an empty string as default ... this will provoke an exception in the module loading !

**Comment by Seb-Solon** [comment]
How it can be that module configuration get overriden by internal alignak configuration? Module are alignak objects usually not part of config object.

**Comment by mohierf** [comment]
If your module tries to read its configuration with default attribute and if the configuration contains something like `port` you will get the `port` attribute of the daemon ... because the `modconf` given to the module initialisation functions contains a very lot of stuff !
