### ISSUE TITLE
LogEvent class is not used but may be useful ...

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#509]
... to be discussed. 

This class parses the monitoring logs built by Alignak and may be interesting for the Logs module.

**Comment by Seb-Solon** [comment]
It was the purpose of this class : parse log broks in module. Actually the idea would be to create Brok that already have this data split instead of a raw string. Converting events to logs (strings) should occurs at the end when outputing not at the beginning.

**Comment by mohierf** [comment]
+1 for your suggestion.

**Comment by mohierf** [comment]
Closed with #774
