### ISSUE TITLE
fix / clean / rewrite the http_daemon module

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#53]
IMHO : too complex / code smells / etc..

and there are often problems when shutting down it because it doesn't join/clean the http threads (properly or at all).
plus the module global `daemon_inst` (declared in http_daemon.py) which is a code smell on its own.

**Comment by gst** [comment]
I'm on it !

**Comment by gst** [comment]
> I'm on it !

ho boy.. but I'm thinking to drop it completely and implement a new one from scratch.. just too messy otherwise..

**Comment by Seb-Solon** [comment]
Done with #189
