### ISSUE TITLE
Arbiter HTTP interface provides uuid for realm property

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#532]
The Arbiter HTTP interface do not provide the realm name for the realms but the uuid:
```
reactionner: {
reactionner-master: {
passive: false,
realm: "d37a81a54f784b8e9d6c0812a4cc98b5",
polling_interval: 1,
alive: true,
manage_arbiters: false,
manage_sub_realms: false,
is_sent: true,
spare: false,
check_interval: 60,
address: "127.0.0.1",
reachable: true,
max_check_attempts: 3,
last_check: 1478093870.726019,
port: 7769
}
},
```

**Comment by ddurieux** [comment]
It's normal no?

**Comment by mohierf** [comment]
No ... this is a side effect of the objects serialization ... there is some source code to get the `realm_name` instead of the uuid ... we should have an object instead of an uuid to make it behave as it should !

**Comment by mohierf** [comment]
I propose to add a `realm_name` property in the *SatelliteLink* class used by all the daemons ... this will only the Arbiter to provide the realm name!
