### ISSUE TITLE
Alignak satellites workers queues named as module python_name

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#539]
The Alignak satellites workers queues are named with the module `python_name` attribute. 

This is a problem with some modules like NRPE booster or SNMP booster because the commands that are attached to a module must be tagged with something like `module_type alignak_module_nrpe_booster` or  `module_type alignak_module_snmp_booster` ...

**Note**: Formerly, satellites used the module `type` property (eg. nrpe_poller, snmp_poller) and we must restore this behavior

**Comment by mohierf** [comment]
Indeed, the module `type` property has been deprecated and replaced with a `module_types` property that is a list of types as they are defined in the example module readme (https://github.com/Alignak-monitoring/alignak-module-example/blob/master/README.rst), this to allow checking if some configuration parameters are matched with installed modules.

**Comment by Seb-Solon** [comment]
I am not sure I am following. Is this an issue to have the module_type value to be the same as the python_name value?

**Comment by mohierf** [comment]
IMO it is an issue because if you want to use several pollers with the same module and different configurations, the module python name is the same whereas the module_alias is different to allow such a configuration

**Comment by Seb-Solon** [comment]
Hum if we have the same module pour several poller don't we have also the same module alias?

**Comment by mohierf** [comment]
No, this is what is interesting with this solution. And I do confirm that it is tested and fully functionnal ...

**Comment by Seb-Solon** [comment]
I don't see how this is supposed to work with the current provided implementation. You only compare with the attribute module_variable instead of python_name. 

Is the idea to copy/paste your module configuration and change the module_alias? So that you load the module_alias A on poller A and module alias B on poller B? Then you tag the command with the module alias A or B ? Pretty sure this is the usage of a poller tag instead. Command have no reason to be bound to a poller actually. Bounding command to a module type was making sens. 

Why not exposing the use case clearly in this issue ? If you know what you are doing it should not take long and this will avoid X comments to have the big picture.

**Comment by mohierf** [comment]
As an example, my current NRPE poller module configuration:
```
## Module:      NRPE Booster
## Loaded by:   Poller

# Allow to bypass launching check_nrpe
define module {
    module_alias            nrpe-booster
    module_types            checks
    python_name             alignak_module_nrpe_booster
}
```

and the daemon that is uing this poller:
```
define poller {
    poller_name             poller-master
    address                 127.0.0.1
    port                    7771

    modules nrpe-booster
    ....
    ....
```

To have dedicated workers in the poller for using this module, the commands **must be tagged** with a string that identifies them else they will be delegated to `fork` workers. To tag the commands, Shinken used a `module_type` property

```
define command {
   command_name    check_nrpe
   command_line    $NRPE_PLUGINS_DIR$/check_nrpe2 -H $HOSTADDRESS$ -t 10 -u -c $ARG1$ -n
   module_type     nrpe-booster
}
```

**Comment by Seb-Solon** [comment]
>>the module alias allows to have several instances of the same module

Following this and you example, I'm trying to understand the use case 

You could have another module 

```
## Module:      NRPE Booster
## Loaded by:   Poller

# Allow to bypass launching check_nrpe
define module {
    module_alias            nrpe-booster2
    module_types            checks
    python_name             alignak_module_nrpe_booster
}
```

and another poller

```
define poller {
    poller_name             poller-master2
    address                 127.0.0.1
    port                    27771

    modules nrpe-booster2
    ....
    ....
```

But then If I want the check_nrpe I would have to declare a check_nrpe2 with nrpe-booster2 module type. 

I don't get the use case where it is more interesting to bind a command to an instance than to the module itself. If you want to ensure check_nrpe only runs on poller-master, then we use poller tag for host/service using this command. 

Is the use case to ensure a check_command to be run in a single worker queue, regardless the poller ? Like, we could have 2 instance of the same module in the same poller but a dedicated queue for something? 

What requirement am I missing?

**Comment by mohierf** [comment]
The module alias is not interesting in the case of this module. There is not much interest  to have several modules for the NRPE booster.

And the requirements is not to run checks in a single worker. Indeed I am not sure of the requirements ... it is only the former Shinken behavior :wink: 

Personnaly I am using the module alias with the NSCA receiver module. I declare two modules with differente aliases and with different configuration parameters: the first listens to the port 15667 and the second listens to 25667 ... this to allow two different NSCA ports on the same server. On the first port I also have NSCA not encrypted and on the second one I have a Xor encryption.
