### ISSUE TITLE
Reactionner module loading exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#541]
Same problem as the poller one: #529 An exception is raised in the reactionner when it tries to unserialize the modules it got in its configuration ...

**Comment by mohierf** [comment]
Moreover it seems that the problem potentially fixed with #529 still occur in some conditions ... I got it again in a test module !

**Comment by Seb-Solon** [comment]
Paste exception please so that we can follow

**Comment by mohierf** [comment]
It is always the same and only one when unserializing: `AlignakClassLookupException` :wink:

**Comment by Seb-Solon** [comment]
The interesting part is which class was not found to be able to add it into the list

**Comment by mohierf** [comment]
Always the same also in this case as explained in the first issue comment: *when it tries to unserialize the modules it got in its configuration ...*

**Comment by mohierf** [comment]
Fixed with #543

**Comment by Seb-Solon** [comment]
The stack trace + exception will always remove any doubt.  "when it tries to unserialize the modules" could raise another exception (let's imagine the Module object has other objects embedded, on this one is faulty?)

Anyway the bug is fixed, I was just trying to fully understand the issue
