### ISSUE TITLE
test_get_start_of_day and test_get_end_of_day are not UTC

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#544]
Those two tests do not pass when running on a TZ aware computer ... on my computer I am not located in UTC and thus thoses tests fail

Is there a problem with the tests or with the tested functions ?

**Comment by Seb-Solon** [comment]
I think it is a bug in the timefreeze lib but I am not sure about it. Maybe we have to fix again the tests. From what I understand the issue was in the time mocking part

**Comment by mohierf** [comment]
Probably, this problem is due to the missing timezone parameter in the Alignak configuration. Thus Alignak considers that timestamps are UTC whereas the host machine is Europe/Paris ... the test behavior may be normal.

But we should add a test for Alignak UTC and Alignak in a dedicated timezone.

**Comment by mohierf** [comment]
@ddurieux : please fix this ...
