### ISSUE TITLE
daemons other than arbiter try to start even without a config file provided

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#55]
but, depending on your installation setup, this can miserably fails because of, already, missing stuffs,
like the "working" directory : 

```
gstarck@taf 10:19 $ which python
/home/gstarck/.virtualenvs/test_alignak_pip_install_venv/bin/python
gstarck@taf 10:19 $ alignak-reactionner
...
[1433513984] WARNING: [Alignak] No config file specified, use defaults parameters
...
    raise InvalidWorkDir(e)
InvalidWorkDir: [Errno 2] No such file or directory: '/var/run/alignak'

Traceback (most recent call last):
... 
  File "/home/gstarck/.virtualenvs/test_alignak_install/local/lib/python2.7/site-packages/alignak/daemon.py", line 429, in change_to_workdir
    raise InvalidWorkDir(e)
alignak.http_daemon.InvalidWorkDir: [Errno 2] No such file or directory: '/var/run/alignak'
```

In this case the alignak was installed within a virtualenv (with `pip install .`),
but in such a case (virtualenv install) : it would be cool / good if the pip install would have set such default config values to something usable, like :  `$VIRTUALENV_PATH/var/run/arlignak` for this specific setting, the others required default settings could also be set to things usable, like `$VIRTUALENV_PATH/var/log/alignak` for the logs directory .. etc ..

So that in the virtualenv, the daemons can be directly started AND usable just by calling `alignak-scheduler` for instance..

To be able to have this feature, the default values for such directives (log dir, run dir, etc..) could be stored in a dedicated module of alignak, say `alignak.defaults` (and the daemons would import and use that) and just be overhidden by the setup/installation (if needed)..

not really required actually but it would have been made like that since the start that would have been incredible - it's never too late :)

**Comment by gst** [comment]
what I mean in the first time is : it's not a problem, imo, that the daemons others than arbiter try to start while no config file given to them.. they'll use all / any default values that they need and that is "hard-coded" somewhere in the code..

what I mean is that :

if we would had that (the "default" coded values) somewhere well defined (still say `alignak.defaults`), and independant from any other thing, then it's rather straightforward to be able to overhidde them with others values for when installed under a virtualenv, for instance.

**Comment by gst** [comment]
> it's not a problem, imo, that the daemons others than arbiter

even the arbiter could run without a config file.. but it's something else given it's special versus the others daemons.

**Comment by mohierf** [comment]
Currently, thanks to #427, all the daemons (even arbiter) can start without a configuration file with default values. Their working dir is the current working directory ...
