### ISSUE TITLE
Alignak statistics: all statistics are timers

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#550]
All statistics sent to StatsD are considered as timers ... it is very much ugly because some are obviously not and the resulting data in Graphite are not usable

**Comment by Seb-Solon** [comment]
What do you mean by timers?

**Comment by mohierf** [comment]
Statsd has several type of metrics: timers, gauges, counters, ... and we only send timers because of the format of the string that is sent:
 `'%s.%s.%s:%d|ms'` (eg. 'alignak.arbiter-master.metric.1|ms)
xhich is always interpreted as a timer by the StatsD daemon

**Comment by Seb-Solon** [comment]
Oh ok, seems legit then to change / support different metric type :)
