### ISSUE TITLE
Packs management

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#551]
Is there still an interest to maintain this feature ? See http://shinken.readthedocs.io/en/latest/14_contributing/packs.html

It seems that it is almost the same as templates

**Note** that currently it is not tested at all ... code coverage is 0

**Comment by ddurieux** [comment]
I think we can usse templates in cfg, so I'm agree to delete this feature

**Comment by Seb-Solon** [comment]
Packs are one of the biggest Alignak strength. It allows you defining services with default config by doing a simple use in a host declaration. Actually, i don't see how a user can have a big numbers of services without using thoses. This allows very factored configuration and to only defined threshold / ecxeption for a host with predefined macros

**Comment by ddurieux** [comment]
With host template (+ this host template has services templates) no?

**Comment by mohierf** [comment]
I think there is a confusion between the checks packs that exist in Shinken monitoring and the packs that are files existing in those checks packs.

**Sorry, my bad**, I provided the only link I found about the packs in the Shinken doc ... but, after a second reading, it is not clear what it is about :/P

 The packs which I am referring to are implemented in the `Pack` class which seems intended to manage a ".pack" file that may exist somewhere in a pack. The `Pack` and `Packs` classes in the *alignak/objects/packs.py* are not at all covered by any unit tests ... and this is what this issue is about.

**Comment by mohierf** [comment]
So, what about the Pack class right now? @ddurieux @Seb-Solon 

>  The packs which I am referring to are implemented in the `Pack` class which seems intended to manage a ".pack" file that may exist somewhere in a pack. The `Pack` and `Packs` classes in the *alignak/objects/packs.py* are not at all covered by any unit tests ... and this is what this issue is about.

**Comment by Seb-Solon** [comment]
It is true that usage is limited at the moment. Are we interested in keep this and use the information that it may contains for other purposes?

* Have version for packs ?
* Export such data to the backend / UI ?

**Comment by mohierf** [comment]
I propose to dismiss this feature for now. Thanks to the backend/WebUI host/service/contact templates will be available to the end-user and it will make it easy to create new monitoring objects. Packs file are not much used today and they will be less used in the future ...

**Comment by mohierf** [comment]
To be discussed for a next version. Feature should be implemented in the backend

**Comment by mohierf** [comment]
Tha Alignak checks packs include some data into the backend with the `alignak-backend-cli` script ... this feature do not look anymore necessary, @ddurieux I propose to decide removing this

**Comment by mohierf** [comment]
Removed packs management
