### ISSUE TITLE
Business rule output exception

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#564]
When evaluating BR output, an exception is raised:
```
Error while re-evaluating business rule: 'unicode' object has no attribute 'last_hard_state_id'
```

this is because the links to host or service are now the object uuid

**Edit**: this is observed in the unit test for the BR output

**Comment by mohierf** [comment]
When the SchedulingItem get all the elements from the DependencyNode, it gets the host/service `uuid` that must be resolved as Host/Service objects before being used to create the BR output.

**Comment by Seb-Solon** [comment]
Fixed right?

**Comment by mohierf** [comment]
Not yet. #571 is not merged :wink:
