### ISSUE TITLE
Tests code coverage inventory

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#572]
From https://coveralls.io/builds/8739254.

This current tests code coverage report, despite 71%, shows several category for low code coverage:

- [ ] non testable features, see https://github.com/Alignak-monitoring/alignak/pull/573

    - [x] HTTP client and interfaces, 
    - [x] threads,  
    - [ ] Worker class,  

-----

- [ ] not tested features, amongst wich:

    - [x] complex expressions,  
    - [x] triggers, see https://github.com/Alignak-monitoring/alignak/pull/580,
    - [x] escalations, see#583
    - [x] flapping, see https://github.com/Alignak-monitoring/alignak/pull/581
    - [x] modulations (checks, macros, ...), see #590, #592, #593, #597
    - [ ] packs (see #551),  

-----

- [ ] not enough tested features

    - [x] properties, see https://github.com/Alignak-monitoring/alignak/pull/576
    - [x] daterange,  
    - [x] realm, see https://github.com/Alignak-monitoring/alignak/pull/577
    - [ ] utilities functions,  
    - [x] host/service extinfo, see https://github.com/Alignak-monitoring/alignak/pull/575

**Note**: I consider a low code coverage for files with a percentage lower than 75%

**Comment by mohierf** [comment]
@ddurieux @Seb-Solon I propose to focus on those subjects before releasing?

**Comment by mohierf** [comment]
Note that HTTP client and daemons interfaces are tested implicitely with the tests that run the daemons (eg. test_launch_daemons) but the code coverage cannot be measured in this context because of the threading mechanism involved in the interfaces.

**Comment by ddurieux** [comment]
Oki

**Comment by mohierf** [comment]
@ddurieux : should you have a look on dateranges and utilities ?
