### ISSUE TITLE
Host extended info 2d_coords and 3d_coords are not implemented

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#574]
Currently, host extended information `2d_coords` and `3d_coords` are not implemented in Alignak.

If you are interested with those properties, feel free to add a comment on this issue

**Comment by ddurieux** [comment]
But the property exist in alignak/objects/hostextinfo.py

**Comment by mohierf** [comment]
Yes but you cannot get it currently ... neither `host.2d_coords` nor `host['2d_coords']` are accepted .... or we should create dedicated functions for those properties?

On another side, those properties should be deprecated in favor of GPS coordinates that we currently manage in the backend and WebUI ... so is it necessary to make an effort actually for this ? I do not think so ...

We'd rather convert the `2d_coords` / `3d_coords` when importing data in the backend ?

**Comment by Seb-Solon** [comment]
If you can't access them that mean something is broken. There is a "fusion" of extinfo into the real object at some point in the parsing.

**Comment by mohierf** [comment]
Ok. Merge is correctly made, no problem with this ... and we can get those attributes with `host.get('2d_coords')` ...
