### ISSUE TITLE
Use "strict" git workflow

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#6]
I would like to follow the workflow present here : http://nvie.com/posts/a-successful-git-branching-model/   (really worth reading !)  

With it : we would/could disable "bare" push of commits to master ; only merge from ~~develop~~ "release" branch would be allowed in master.

master -> THE master branch, should always only point to the last stable released version.
develop -> The branch in which others "dev" branches are merged. Let them be feature or fix branches.

When we would (want to) be in a  "freeze period" for preparing the next prod release : `git checkout -b release-$x.$y develop` and last bug fixes would be merged in this temporary release branch. 
Once we assume it's ok : `git checkout master && git merge --no-ff release-$x.$y && git tag $x.$y`

**Comment by ddurieux** [comment]
I think it's too complex.

I think nodoby commit directly, only use PR, a dev check code and check if tests are in the PR, if yes and tests pass, merge the PR in master branch.

So we will have only one branch, the master, and all code in this branch is stable so we can release when we want

**Comment by gst** [comment]
> I think it's too complex. 

It's only another level of branch, and the whole thing can be resumed as this quite simple tree : 
```
  master <--  release-x.y <-- develop <-- fix_or_feature_PR
                      \--- fix_only_PR
```

**Comment by ddurieux** [comment]
Always too complex :p, read my comment ;)

**Comment by gst** [comment]
I read it ;) and what you found too complex I found it appropriate actually ;)
that's basically on the line of "Divide and conquer"  or "keep things (a little more) separated".

This is to have a crystal clear distinction between merged commits/PR which have passed the tests (*develop* and/or *release* branches) and actually really **released** (normally stable) version (master branch)..

see it ?

**Comment by aviau** [comment]
There are advantages to using a ``developp`` branch.

For example: when a bug is found in the latest release, it is fixed in the ``master`` banch (not ``devleopp``). Then it is released again. It makes more sense to rebase ``developp`` on ``master`` than merge a the patch in ``developp``. New features should be built on top of what is released.

**Comment by ddurieux** [comment]
See you sat master 'normally released'...
We will have too many branches and I thinkit will require more time to manage them

**Comment by aviau** [comment]
> We will have too many branches and I thinkit will require more time to manage them

I don't really understand the complexity of managing branches.

**Comment by ddurieux** [comment]
For develop and master branch I'm now agree with you ;)

But not sur have xx branches because after all people not know on what branch make the pr

**Comment by mohierf** [comment]
Whatever the final decision ... I think that this decision should be written down in a "How to contribute" file in the root directory, with clear examples. It should avoid wrong usage of the process for not regular contributors

 Best should be to open a page in the project Wiki ?

**Comment by gst** [comment]
> But not sur have xx branches because after all people not know on what branch make the pr

we will kindly remind them if they would choose the bad one to merge against ;)

**Comment by ddurieux** [comment]
Don't forget too one release = one tag, so we can return on a tag if required ;)

**Comment by ddurieux** [comment]
mohierf a file on  root and a page on the doc in readthedoc site

**Comment by mohierf** [comment]
@ddurieux : yes ... but if the rules are different than the one described on readthedoc ?

**Comment by ddurieux** [comment]
Alugnak readthedo not yet created but very soon ;)

**Comment by mohierf** [comment]
Should we agree on this for the next release:
```
  master <--  release-x.y <-- develop <-- fix_or_feature_PR
                      \--- fix_only_PR
```

From: http://nvie.com/posts/a-successful-git-branching-model/   (really worth reading !)

**Comment by Seb-Solon** [comment]
Having a specific release branch for backport can be good but I am not sure about your scheme here. You would like to merge into develop then into release and then into master?

**Comment by mohierf** [comment]
Each **fix** or **feature** is made in a dedicated branch.
This branch is first merged to **develop** that is used to integrate all fixes and features.
When we want to release, we create a **release** branch from develop to make a RC version
For fixing bugs found in the RC, we create a **fix** branch that will be merged to the release branch
When the version is stable enough, we merge **release** to **master**

This process is clean and simple enough

**Comment by Seb-Solon** [comment]
I don't see the difference between develop and release then. If we want to only merge fixes in develop it is up to the team (Freezing time). Feature branch will always exist even if not merged right?

The fact you think we may need a release branch may indicate that you don't feel safe enough in develop. Is is correct?

**Comment by mohierf** [comment]
The main interest in the release branch is to have a still version of the repo while the develop branch mau contain fixes and features not yet released. 

Let's say we release a 1.0-RC1 version and we have many issues. We will be able to fix the issues gently in the develop branch and keep this RC1 version untouched until we find develop enough stable to release a RC2.

Furthermore, it is not a constraint to have this branch ...

**Comment by Seb-Solon** [comment]
I don't see really the advantage of creating a branch for every release. Release are made by tag on a branch, not by creating a branch itself in my opinion. You still can have RC1/2/3 on the master branch. People that are willing to take only stable stuff will only pick non-rc TAG right?

I don't see what is the point of master on what you suggest. I also do see what are the limitation of the current model.

Having a branch for a specific release so that we can backport patch is fine however.

**Comment by mohierf** [comment]
It is your last sentence that makes me prefer having a release branch :wink:

**Comment by Seb-Solon** [comment]
My last sentence explains why it can be an exception for a long term support, not a required branch in the development process.

**Comment by ddurieux** [comment]
A branch for release is good to manage the fix versions, so
* develop = current dev (no next major version)
* release = the major x.x version where we will tag x.x.x, x.x.y ... (so fixed /minor versions)
