### ISSUE TITLE
fix / clean / rewrite the http_client module

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#60]
Don't use anymore pycurl.

I propose to use the requests (http://docs.python-requests.org/) module.

**Comment by gst** [comment]
linked to https://github.com/Alignak-monitoring/alignak/issues/53

**Comment by ddurieux** [comment]
I'm not against this, but what we will win with python-requests instead curl?

**Comment by gst** [comment]
requests is greatly more appropriate / easy / pythonic, 

and also it's usable/compatible with `pypy` while pycurl isn't ; which is the main blocker for us to try it (we could - quite very easily - obtain lot of performance wins)

http://stackoverflow.com/questions/15461995/python-requests-vs-pycurl-performance -> http://stackoverflow.com/a/15462207/2451329

so I would like to take the opportunity to completely clean the http_client module and rewrite it using requests.

**Comment by gst** [comment]
ongoing..  GET & POST seems already good..

**Comment by gst** [comment]
Seems good.. *seems* ..

**Comment by gst** [comment]
has been merged !
