### ISSUE TITLE
Alignak versionning

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#601]
Following recent discussions, I summarize in this issue.

Alignak versions numbering should perharps follow PEP440 used by PIP: https://www.python.org/dev/peps/pep-0440/ ?

As a sum-up: M.m.f:
 - M, major release (breaking changes)
 - m, minor release (new features)
 - f, fix release (bug fixing release)

To be discussed...

**Comment by ddurieux** [comment]
ok for me ;)

**Comment by algorys** [comment]
:+1: for me too.

Do you also plan to do something like that ?

`alignak 1.2` need at least `backend 1.2`, `webui 1.2`, `app 1.2` ....

**Comment by mohierf** [comment]
We should. The main idea is to try keeping major versions (at minimum...) compatible. 

Alignak is the central point of the system, **but** it is not the central point of the software ecosystem. It is the backend that is connect every component ...

 the compatibility between Alignak and the Backend is assumed by the Backend modules, and the compatibility between the Backend and the WebUI is assumed by the WebUI.

**Comment by mohierf** [comment]
According to this issue, Alignak Milestones are defined with `M.m` only ... the `f` is only for the fixes release.

**Comment by ddurieux** [comment]
You're right ;)

**Comment by mohierf** [comment]
The next released version will be tagged as 1.0.0
