### ISSUE TITLE
Remove direct routing from receiver

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#604]
As discussed in #316 and as observed in the code and testts, the direct routing feature of the receiver must be set for external commands to be correctly handled by Alignak.

As of today the Arbiter never need to have a module (no more old Nagios modules, the external commands are managed through a receiver module, ...) so the direct routing feature shoul be removed from the receiver

**Comment by ddurieux** [comment]
+1

**Comment by ddurieux** [comment]
Remove parameter in the config file
