### ISSUE TITLE
Statictics about internal 

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#608]
We have yet metrics send to statsd, but I add all metrics we need: 

* global time of the scheduler loop (loop = execute all _recurrent_works_)
* time of execution of each _recurrent_works_ items
* time (all 5 seconds for exemple) as average of complete time of check creation in scheduler -> poller start command execution + end command execution to consume result in scheduler.

**Comment by mohierf** [comment]
As explained in #550, all metrics sent are currently timers ... 

your last request is the average checks execution time, right?

**Comment by mohierf** [comment]
What about this @ddurieux ?
