### ISSUE TITLE
fix/clean wait_for_initial_conf()

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#61]
it's not anymore valid since the old change from Pyro to http for communication.

if you call it with say 10 : `wait_for_initial_conf(10)` then you will have to wait 10 secs, even if a new conf is received meanwhile : 

```python
def wait_for_initial_conf(self, timeout):
    cur_timeout = timeout
    ...
    elapsed, _, _ = self.handleRequests(cur_timeout)

def handleRequests(self, timeout, suppl_socks=None):
    socks = []
    if suppl_socks:
        socks.extend(suppl_socks)
    ...
    ins = self.get_socks_activity(socks, timeout)

def get_socks_activity(self, socks, timeout):
    if socks == []:
        time.sleep(timeout)
        return []
```

So `wait_for_initial_conf(x)` is the same as `sleep(x)` which is not what is intended..

**Comment by Seb-Solon** [comment]
Partially fixed in #195
