### ISSUE TITLE
Hosts are always DOWN

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#617]
With the most recent develop branch version, hosts are always seen as DOWN!

Thanks to @spea1

**Comment by mohierf** [comment]
```
git reset --hard d5202054385d6b8433ab993593f3ee76e8c10e2e
```
restores a fully functional version!

The bug was introduced in the *actions.py* with `self.exit_status = 3` in the object initialization.

Quite strange that the tests did not detected this !

**Comment by mohierf** [comment]
Ok, got it! The problem does not happen in the poller but in the scheduler when he gets back the actions from the pollers. The `Check` objects are initialized from the serialized objects and they all get an `exit_status` set to 3 (unknown ...).

The current test for the checks results is only testing the checks inside the poller

@Seb-Solon : here is the explanation

**Comment by ddurieux** [comment]
I think it's come with my PR on serialize checks and actions to poller

**Comment by mohierf** [comment]
It is fixed with #619

**Comment by mohierf** [comment]
As another side effect that I noticed with this problem ... the notifications are sent very rapidly by Alignak because the action `creation_time` is set as now when the action id unserialized. Thus, alignak considers that the notification must be sent immediatly because it was not yet sent ...

 I flooded my SMTP relay and got banned :/P

#619 solves both problems.
