### ISSUE TITLE
Backend connection parameters

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#632]
You should add a `token` parameter in the `[backend]` section of the configuration file. The *token* is provided by the backend when you use the */login* and it may included in the configuration file instead of the username / password. It is a more secure solution ...

**Comment by ddurieux** [comment]
?? You have yet token in the alignak backend module configuration.

**Comment by mohierf** [comment]
Sorry. Wrong repo :disappointed:
