### ISSUE TITLE
Use Project github

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring/alignak#638]
I don't know if you've already a **Design document** ?

Something like a doc who describe goals of version, wanted feature and all the other things in the genre. In fact all that can help to describe Alignak project for dev (and maybe contributors also).

Github offers a Project tab who maybe help for this ?

That maybe also help to see what is done or not.

**Use cases:**

- Packages done for X version are : debian, fedora,...
- Alignak 1.5 will offer : faster, compatible python3, ...
- Which things are required for contributing projects (like for alignak modules)
- Which version are compatible with Alignak 1.5

What do you think ?

**Comment by mohierf** [comment]
AFAIK, this Design Document does not existyet, but I think that it is a must-have once we release the 1.0 version!

I had a look to the Project feature of github and it is an interesting feature. Having a Kanban like dashboard will help to cross-reference issues and milestones for new (update) features implementation.

:+1: for this
