### ISSUE TITLE
Move packaging stuff to the packaging repo

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#655]
Jointly with this [alignak packaging issue](https://github.com/Alignak-monitoring/alignak-packaging/issues/18), some modifications may occur in the alignak main repo:

- [ ] the *bin* directory contains startup scripts for Debian/Ubuntu SysV (*init.d) and for FreeBSD (*rc.d*), we should move this to the alignak-packaging repo which already contains the systemd scripts

- [ ] the *bin* directory contains a *default/alignak.in* file used by the init.d scripts. This file is intended to become the main entry point for Alignak installation ([as explained in this issue](https://github.com/Alignak-monitoring/alignak-packaging/issues/18)). As such, we may move this file to another folder and provide a default version for the packagers.
    **[edit]** Instead of re-using the *alignak.in* file used by the init.d scripts we may have another dedicated file with a standard format compatible with any OS. To be tested with an ini file format...

- [ ] the distutils python *setup.py* script must be updated according to those new rules

- [ ] the *dev* directory contains some script that are intended to be used by the developers to start / stop alignak. We must promote using those scripts rather than the *bin/init.d* scripts when alignak is used from the git repository

**Comment by mohierf** [comment]
@ddurieux @Seb-Solon : what do you think about this proposal? Having all the packaging stuff in the [alignak packaging repo](https://github.com/Alignak-monitoring/alignak-packaging) seems legit to me. 

I do not understand why it was necessary to have a dedicated repo for the packaging, and I did not found an explanation of this choice, but it exists... and, as such having init.d / rc.d scripts in the alignak repo is a non-sense tha may lead people to misunderstanding as it did for me :wink:

**Comment by mohierf** [comment]
@algorys: As of #649, you should consider the 4th item in my comment. We shoul dpromote using the *dev* folder scripts to run alignak when one cloned the repository instead of using the *init.d*  scripts that are intended to be used as system start scripts for a system V Debian installation.

The alignak tutorial should take this into consideration also ... it would be really better. I am having a look at those scripts to confirm they are fully functionnal :wink:

**Comment by ddurieux** [comment]
From my memory, we had split because the tagging of packages will be not synchronized with alignak release management

**Comment by mohierf** [comment]
Closing to favor #656
