### ISSUE TITLE
Create an Alignak permissions script

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#674]
What is it about? Let's sum-up what's ongoing as of now when Alignak is installed... and what is the current problem.

When installing from a distribution packaging, or from the source code, the Alignak application code and configuration files and folders are located to their appropriate folders and are owned by the `root` user.

As discussed during the Dec 29th meeting, it should be better that the alignak configuration files and folders perrmissions are set to `w` for the `alignak` user. Else it is not possible to run the alignak daemons without sudoing...

We should create a new script *dev/set_permisssions.sh* to set the correct files/folders ownership and permissions for the `alignak` user, as recommended in the console dump at the end of the setup script:
```
          == You should grant the write permissions on the configuration directory to   ==
          == the user alignak:                                                          ==
          ==   find /usr/local/etc/alignak -type f -exec chmod 664 {} +
          ==   find /usr/local/etc/alignak -type d -exec chmod 775 {} +
          == -------------------------------------------------------------------------- ==
          ==                                                                            ==
          == You should also grant ownership on those directories to the user alignak:  ==
          ==   chown -R alignak:alignak /usr/local/var/run/alignak                      ==
          ==   chown -R alignak:alignak /usr/local/var/log/alignak                      ==
          ==   chown -R alignak:alignak /usr/local/var/libexec/alignak                  ==
```

**Comment by Seb-Solon** [comment]
> it should be better that the alignak configuration files and folders perrmissions are set to w for the alignak user. Else it is not possible to run the alignak daemons without sudoing

If i remember correctly we were trying to find example to see how other package solved this issue. Like apache. I can't remember what was the outcome of that. 

Still this script is needed for "dev" env in my opinion

**Comment by mohierf** [comment]
The outcome was that one is obliged to have some root permission to edit the configuration files and even to view the log files.

The script I introduced is in the *dev* folder and is intended for the developers. It is not used by the python setup.
