### ISSUE TITLE
BP Rules - take into account acknowledgements or downtimes

### ISSUE THREAD

**Issue by fpeyre** [Alignak-monitoring/alignak#685]
Originaly this is an issue open on Shinken ( https://github.com/naparuba/shinken/issues/1825 )
I have made a PR for this issue ( https://github.com/naparuba/shinken/pull/1837/files )

The use case is:
I have a service/host used inside a BP rule. If this service/host is in downtime/acknowledged, I want it's state is considered as OK when the BP rule is estimated.

How to implement : 
My idea is adding two new variables for an host/service, deactivated by default , ```business_rule_downtime_as_ok``` and ```business_rule_ack_as_ok```.
When this variables are activated, the object in downtime/acknowledged is considered as OK.
When deactivated, we keep the current behaviour.

**Comment by ddurieux** [comment]
Not really agree with all the modification to do. I explain:

I think the actual behavior is wrong, if a host / service is in downtime or acknowledge, the bp_rule must consider it as OK/UP. I'm not agree to have again parameters to change this behavior
