### ISSUE TITLE
clean the `alignak.log` module and its load_obj() "hack"

### ISSUE THREAD

**Issue by gst** [Alignak-monitoring/alignak#70]
find a better way to handle the feature that `alignak.log.Log.load_obj()` permits ..

actually : depending on the conditions, sometimes the load_obj() method is called multiple times, which results in so many ("Brok"-)log handlers being created and attached to the logger.. which can finally be bad because this results in the logs being dispatched multiple times to different "destination" but you are not anymore sure what they are. On its own this can be bad and is almost never desirable (at least as it is right now done).

```python
    def load_obj(self, object, name_=None):
        """ We load the object where we will put log broks
        with the 'add' method
        """
        global _brokhandler_
        _brokhandler_ = BrokHandler(object)
        if name_ is not None or self.name is not None:
            if name_ is not None:
                self.name = name_
            # We need to se the name format to all other handlers
            for handler in self.handlers:
                handler.setFormatter(defaultFormatter_named)
            _brokhandler_.setFormatter(defaultFormatter_named)
        else:
            _brokhandler_.setFormatter(defaultFormatter)
        self.addHandler(_brokhandler_)
```

the `global _brokhandler_` is on its own a code smell here..

**Comment by mohierf** [comment]
Closed with #427
