### ISSUE TITLE
Package for Debian jessie not found

### ISSUE THREAD

**Issue by efficks** [Alignak-monitoring/alignak#729]
I'm trying to instal Alignak through the debian repository for Debian jessie.
However, i'm always getting the following error :

> Unable to locate package alignak

When I do apt-cache, only "alignak-all" package is available. Is there something wrong in the packaging?

**Comment by hvad** [comment]
Hi,
It's normal... Alignak projet don't have official debian package. 

But you can try this -> http://alignak-doc.readthedocs.io/en/latest/02_installation/deb_packages.html.

Bye

**Comment by mohierf** [comment]
@efficks : beware that currently the packaging is not up-to-date ... we are on the way to release and we recently broke the packaging. Waiting for a cleant package, please consider installing from the git repository:  http://alignak-doc.readthedocs.io/en/latest/02_installation/sources-pip.html#installation-from-the-git-repository

Feel free to join on IRC #alignak if you need some more help 😉

**Comment by efficks** [comment]
@mohierf @hvad
I have experience in packaging and continuous integration system. I can help you in setuping the whole system if you need help.

**Comment by hvad** [comment]
HI,

@efficks i work on Fedora/EPEL packaging but not on Debian project. You can open itp on Debian project if you want.

Best regard

**Comment by mohierf** [comment]
New packages will soon be available on bintray. 

Alignak packaging and download repositories for Linux/Unix is done thanks to the Bintray software distribution: https://bintray.com/alignak/.

**Comment by mohierf** [comment]
Packages are now available ad built automatically with Travis CI
