### ISSUE TITLE
Acknowledging an host should acknowledge all its problems

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#732]
Wehn acknowledging an host problem, Alignak should acknowledge all its services that are problems.

Currently, setting an host acknowledge let all the services of this host appear as problems. 

If the host services are actively checked, Alignak will not check them anymore...

If the host is passively checked, we may still receive passive checks for the services, but it is not a problem to set them as acknowledged...

**Comment by algorys** [comment]
I'm fully agree with @mohierf for this feature. It seems more logical.

**Comment by ddurieux** [comment]
I'm not agree, be acknowledge not mean not check. so do the checks is ok for me.
I think you mean do the services of the host in acknowledge too, it's not linked to the check.
You can have the case of the host check check the ssh and not answer but a service of the host works (special case but possible)

**Comment by mohierf** [comment]
To be discussed ... because you do not monitor any passively check hosts, you do not think this is necessary. This feature is a must-have when you are monitoring seom passively checked hosts, because, when an host is DOWN, all its services will be problems after their freshness period !

**Comment by ddurieux** [comment]
ok for passive, it's right, so perhaps do this only for all host services when the host is passive only no?

**Comment by mohierf** [comment]
Yes, why not? Let's discuss this tomorrow ...

**Comment by mohierf** [comment]
Following our discussion, the acknoweldge request for an host will acknowledge all the faulty services of this host. As of it https://github.com/Alignak-monitoring/alignak/pull/733 can be merged.
