### ISSUE TITLE
Propose more sample cfg files

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring/alignak#735]
Currently, I think we missing some `cfg` files example...

`services.cfg` is empty for example.

Can we have a total example file (commented if needed) with:

- a host
- a service
- a command
- others ?

For beginners who has never set this kind of files it should be helpfull :wink:

**Comment by mohierf** [comment]
Not sure it is Alignak responsability to add all those information. The doc refers to the Nagios configuration file format which is, IMHO, a good starting point.

Furthermore, the next version will remove all those configuration file to focus on the backend data model... I close this issue. Feel free to reopen if more discussion about this matter looks legit 😉
