### ISSUE TITLE
Scheduler retention log brok, which scheduler?

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#742]
When the scheduler creates a monitoring log for the retention (load or save), the only provided information is `RETENTION SAVE` or `RETENTION LOAD`. The scheduler should indicate which realm is concerned: `REALM ALL RETENTION SAVE` or `REALM ALL RETENTION LOAD`

**Comment by ddurieux** [comment]
The description is not good, we not have the realm but the scheduler name
