### ISSUE TITLE
Ack on sub sub realms

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#744]
When the arbiter receives an external command for an host in a sub sub realm, the command is not sent to any scheduler ...

As an example, my configuration is:
- realms: All -> South -> South-East
- hosts: `pi1` and `pi2` in realm South-East
- hosts: `passive01` and `passive02` in realm South

Acknowledge sent to `passive-01` is propagated, but acknowledge for `pi1` is not propagated.

Perharps a solution with the refactoring of #743 ?

**Comment by ddurieux** [comment]
Linked to #422 and #743
