### ISSUE TITLE
Scheduling a downtime for an host should acknowledge all its problems

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#752]
As for #732 (acknowledges) we should have a similar behavior for hosts downtimed.

When scheduling a downtime for an host problem, Alignak should acknowledge the host problem and all its services that are problems. 

Currently, scheduling a downtime for an host, let the host and all its services of this host appear as problems.  A downtime scheduling is an implicit acknowledge of the probems ... if one schedule a downtime, then one is aware about the problems 😉

**Comment by ddurieux** [comment]
It's better put a downtime too for service no? seems more logical have downtime instead acknowledge no?

**Comment by mohierf** [comment]
Not necessarily ... acknowledging is meaning: **"I have a problem and I am aware about it** and that is enough to acknowledge the services of an host on which you scheduled a downtime.

**Comment by ddurieux** [comment]
Not really, I take an exemple:

You downtime a host for sunday between 10 and 12 a.m
you know you will reboot the server 2 times, if you put an aknowledge on services, after a first reboot the aknowledge will be end and at the second reboot, the service will be critical. 

In this example we see put the same downtime on service is the better solution
