### ISSUE TITLE
Alignak daemon can not create its log file

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#765]
I am currenly logged-in as a non-root user and nor logged-in as `alignak` user. I ran the */dev/set_permissions.sh* script, thus having the recommended ownership and rights on the */usr/local/var/log/alignak* directory.

Whatever the values in the `user` and `group` properties of the daemon ini file, when starting Alignak with the */dev* running scripts:
```
[2017-03-24 08:27:26 CET] ERROR: [alignak.daemon] Opening the log file '/usr/local/var/log/alignak/arbiterd.log' failed with '[Errno 13] Permission denied: '/usr/local/var/log/alignak/arbiterd.log''
```

I suspect the log file to be created before the daemonization :/

**Comment by ddurieux** [comment]
It can be logical no? to have log at the beginning, so before the daemonize

**Comment by mohierf** [comment]
To be discussed ...

**Comment by mohierf** [comment]
Indeed I agree that it is not a bug but a logical, hence disappointing, behavior...

The default `set_permissions.sh` script creates an `alignak` group/user that is supposedly used in the daemons ini configuration files. Perharps we may allow to set the permissions for another user if one need to run alignak as an alternate user ...
