### ISSUE TITLE
Missing daemons for a realm - workaround

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#798]
With the whole Alignak stuff installed, it is possible to update the monitored configuration thanks to the WebUI, nice ! But ... what happens if one adds a realm in the configuration, and then an host in this new realm?

The configuration gets realoaded by the Arbiter and then its check is failing because no daemon exist for the newly created realm! All the Alignak framework is stuck and no hosts are monitored anymore !

Two ideas to be discussed:

1. before reloading a configuration, store the former configuration and restore it if the new one fails to load properly?

1. create a fake scheduler/broker/poller daemon for the newly created realm?

The first solution seems quite difficult to implement currently because of the current coding ... but the second solution would not be that difficult to implement ... to be tried

At minimum, some logs must be raised to alert about this situation !

**Comment by mohierf** [comment]
Trying to implement the second solution...

**Comment by fjvt** [comment]
Why not simply refuse to add a host to a 'non properly configured' realm ? IE a realm which has no 'poller/scheduler's configured ?

**Comment by mohierf** [comment]
It is not as simple as it appears ... curretnly the webui do not know if a realm is properly configured with all its daemons

**Comment by mohierf** [comment]
Progressing: creating a daemon configuration on-the-fly is easy but the daemon process is not existing.

Two solutions:
- set the hosts attached to the unknown realm as not monitored and accept the configuration as valid
- start the missing daemons process from the arbiter

**Comment by mohierf** [comment]
**Note** that if the scheduler was able to `manage_sub_realms` all concerned hosts should be attached to the default scheduler !

**Comment by mohierf** [comment]
The solution I am trying to fix this problem is to parse the configuration slightly differently to detect all the necessary realms and daemons. This allows to identify the missing daemons (eg. the one not declared in the configuration) and then make those daemons started by the arbiter.

A necessary modification of the launch script takes place to specify the daemon HTTP port and name, this to make it different from the other daemons.
