### ISSUE TITLE
private functions of class in top of class (it's cosmetics & better to read the class)

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#81]
For better read of code, put all private functions (like **str**) immediately after class declaration avec **init** .

We have some classes where we have these functions anywhere in class

**Comment by gst** [comment]
I agree it's better (for readability and understand-ability of a class behavior) to keep most of those little (mostly usually) functions near the top of a class definition.

we have no enforced nor defined rule about that I think; 

By the way aren't there some pylint / pep8 rule(s) about this kind of "code placement" ??

Now this isn't a fun task at all..

**Comment by ddurieux** [comment]
Not find :/

**Comment by mohierf** [comment]
I am closing this... not many interest. Re-open and argument if needed.
