### ISSUE TITLE
$NOTIFICATIONRECIPIENTS$ macro on the reactionner is empty

### ISSUE THREAD

**Issue by fjvt** [Alignak-monitoring/alignak#818]
When using the $NOTIFICATIONRECIPIENTS$ you get n/a back. 

some other macro's do the same but in this particular case (standard notification that is normal)

$COMMENT$ -> Empty in case of a normal notif
$AUTHOR$ -> also empty in case of a normal notif

haven't had the opportunity to test those ...

**Comment by mohierf** [comment]
I do confirm that the $AUTHOR$ and $COMMENT$ must be empty for a standard notification but they should be valued for a downtime notification, and it is not the case currently ... 🐛
