### ISSUE TITLE
No re-notification problem when state is changing

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#821]
See the test `test_3_notifications` ...

When `notification_interval` is set to 0, notifications are never re-sent to the same contacts, but when the state of the host/service changes, a notification should be raised, but it is not raised ...

What I expected was a notification for WARNING, and then one for CRITICAL, but only the first one is raised.

**Comment by fjvt** [comment]
Correct. A notif should be sent out if a hard state change occurs (stateA to any other state (ok, crit,unknown)

**Comment by mohierf** [comment]
On the IRC channel:
```
<frv>i think nagios does it the same way
<frv>HARD warn -> HARD crit doesn't give a notif
<frv>although here
<frv>https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/statetypes.html
<frv>it says it should
<frv>i seem to remember my tests that it didn't always do that
<frv>https://support.nagios.com/forum/viewtopic.php?f=7&t=10735
<frv>lots of people have struggled with that in the past
<frv>sometimes it worked , sometimes it didn't
<frv>good idea to make sure alignak works this way
<frv>WARN-> CRIT or CRIT->WARN should always give a notification
```

**Comment by mohierf** [comment]
As @hvad said: it is of a great importance to notify when a state changes from WARNING to CRITICAL 😉
