### ISSUE TITLE
Travis build and code coverage

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#826]
To improve the Travis build execution time, the Alignak tests are splitted in 3 tests suites:
 - unit, for the unit tests
 - run, for the daemons running tests
 - load, for the daemons load test

As such, the code coverage measurement can not be a global one, becauses all tests suites are executed in their own context.

At the time of writing, the code coverage for Alignak is up to 89% but only the unit tests suite is reporting to the coveralls.io and its code coverage is 81%.

A Travis `after_all` feature would help to get a global code coverage, as stated in this issue: https://github.com/travis-ci/travis-ci/issues/929, but the feature is not yet available

**Comment by mohierf** [comment]
As a workaround, including one of the daemons run tests in the unit test suite would reflect a more real coverage ?

**Comment by ddurieux** [comment]
As I read in https://docs.travis-ci.com/user/build-stages, we could use stages but require a shared folder on remote computer to store all coverage files and the last commit get all and generate the coverage. We could use one of my server through scp(ssh)
