### ISSUE TITLE
export to kernel.alignak.io isnot available

### ISSUE THREAD

**Issue by aviau** [Alignak-monitoring/alignak#86]
Hello,

I am getting this:

```
[1434467974] ERROR: [Alignak] Cannot find python lib crypto: export to kernel.alignak.io isnot available
```

Wasn't sending usage statistics disabled in Alignak?

**Comment by Seb-Solon** [comment]
It's during import. We should just put import in the _encrypt function and not at the top because it's not really a dependency. 

Otherwise we could maybe just remove the error that make no sense.

**Comment by ddurieux** [comment]
We can remove references to kernel.alignak.io (it's for statsd)

**Comment by aviau** [comment]
So there are no usage statistics sent anywhere?
