### ISSUE TITLE
poller in sub-realm not re-send commad result to the schedulers

### ISSUE THREAD

**Issue by ddurieux** [Alignak-monitoring/alignak#869]
When have mutliple scheduler (in case have multiple relams) and only 1 poller, the return of the check not go from poller to scheduler

**Comment by mohierf** [comment]
AFAIR this is fixed in the load-test-suite pull request ...

**Comment by ddurieux** [comment]
With the version of friday of load-test-suite I have this problem...

**Comment by mohierf** [comment]
I noticed the saem behavior with the reactionner. When the poller/reactionner are configured to manage sub-realms, the actions results do not always come back to the scheduler. Indeed, only one scheduler gets its results back ... :/
