### ISSUE TITLE
Namespace Python

### ISSUE THREAD

**Issue by Seb-Solon** [Alignak-monitoring/alignak#90]
* Edit setup.py to create the name
* Add doc to develop a new module
* Edit module template (dummy_modules)

Linked to #97

**Comment by Seb-Solon** [comment]
@titilambert  can you confirm step one is done ? May I gently ask you to do the other? I'm not 100% sure what to write for the doc and how to edit the new module.

It's basically import alignak.basemodule.Basemodule  ? The whole trick is in setup.py to install in the namespace right?

**Comment by titilambert** [comment]
missing: 
* Add doc to develop a new module
* Edit module template (dummy_modules)

**Comment by Seb-Solon** [comment]
It's done but we still have the issue with __init__ file from a module that override the one from the core.
ping @titilambert @gst @ddurieux if you have any news/idea about this.

**Comment by ddurieux** [comment]
Not yet find a solution

**Comment by Seb-Solon** [comment]
Fixed by  : Alignak-monitoring/mod-example@0a58f3709369aca1505724811f90c38b339ac6e7
