### ISSUE TITLE
Contact notification ways management

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#911]
A `contact` object may have some notification ways and some notification commands in its configuration. the real contact notification commands are an union of the contact notification commands with those inherited from the contact notification ways.

Currently, using the contact `host_notification_commands` property only provides the contact commands and not the NW inherited commands.

This has an ugly side effect. Especially, in the `alignak-backend-import` script that relies on the object properties ...

**Comment by spea1** [comment]
Can be closed -> https://github.com/Alignak-monitoring-contrib/alignak-notifications/issues/15
Thanks
