### ISSUE TITLE
"Alignak internal metrics" Grafana dashnoard  missing data

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring/alignak#913]
![alignak-dashboard](https://user-images.githubusercontent.com/20840532/29943065-43bd3cf8-8e98-11e7-91f1-271ff382bef0.jpg)
missing data for:
- Scheduler master checks
- Scheduler master notifications
- Arbiter daemons monitoring
- Arbiter get objects
- Push external commands
- Poller master - workers queue size
- Scheduler master total loop duration
- Scheduler master loop duration details

**Comment by mohierf** [comment]
This is because your Grafana dashboard is not up-to-date. I changed some metrics organization inside the source code but I did not yet published the new dashboard :/

![image](https://user-images.githubusercontent.com/2932687/29954533-e9f68b02-8ed8-11e7-8a70-d6883937452e.png)
