### ISSUE TITLE
deb&rpm files not found

### ISSUE THREAD

**Issue by LionelR** [Alignak-monitoring/alignak#930]
Alignak can't be installed via deb or rpm packages, unlike described in the doc.
The repo http://alignak-monitoring.github.io/repos/ returns a 404 error.

**Comment by mohierf** [comment]
Hi @LionelR I know that @ddurieux will manage this problem during the week-end. We released a version 1.0 during the week but did not yet took care about the packaging :/

**Comment by LionelR** [comment]
Ok, no problem, it was just for information :)

**Comment by mohierf** [comment]
@hvad is currently working on the RPMs for Fedora and EPEL

**Comment by ddurieux** [comment]
The debian packages will be available next week ;)

**Comment by hvad** [comment]
Hi,
Alignak RPMs are available for RHEL/Fedora https://apps.fedoraproject.org/packages/alignak.
Best regard

**Comment by mohierf** [comment]
Doc updates in progress

**Comment by hvad** [comment]
For Fedora, dnf install alignak-all ;-)

Envoyé de mon iPhone

**Comment by mohierf** [comment]
@hvad: would you mind having a look at this doc chapter ? http://docs.alignak.net/en/develop-environment/02_installation/index.html

And please propose modifications to help installing on Fedora 😉 Comment this issue or mail me what is to be modified, I will integrate in the current doc version that I am preparing

**Comment by mohierf** [comment]
See the new python3 branch and the Alignak bintray repositories: https://bintray.com/alignak/
