### ISSUE TITLE
Configuration mixing flat files and backend, how-to?

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#939]
Some users would like to keep a flat-files configuration because they manage the configuration in a version control system.

How to deal with such a configuration? How to version control the configuration in Alignak backend with the API?

This issue is to discuss this matter... all ideas and experience are welcome

Several ideas:

**1.** import from flat files into the backend on each configuration modification (`alignak-backend-import` script

**2.** create a new `alignak-backend-update` script that manages the differences between two flat files configuration and that updates the backend accordingly

**3.** maintain the monitored objects in JSON configuration files that would be easily imported/updated in the backend thanks to the `alignak-backend-cli` script

**Comment by mohierf** [comment]
Solution 1:
-----

importing all the configuration on each modification is an heavy solution that is really not acceptable! It would imply many modifications in the `alignak-backend-import` script to simply update some information...

👎

**Comment by mohierf** [comment]
Solution 2:
-----

this solution should be based on a new script that will load two configurations like Alignak does and tha twill compare both configurations. This may be tricky to maintain when the Alignak backend model is updated.

This solution should also be based on a diff file provided as an input, but it will also be tricky to maintain ... 
👎

**Comment by mohierf** [comment]
Solution 3:
-----

this solution is based on a flat files configuration encoded with JSON and backend updates made with the `alignak-backend-cli` script that still exists.

Many advantages:
 - JSON is an easy to parse file format and raising differences between two files is not very complicated
 - only the different information is pushed to the backend that natively support this data format
 - Alignak checks packs with templates still use this script and file format

 As such it looks as the best candidate for matching the requirements
👍 👍 👍

**Comment by flaf** [comment]
Hi,

Yes solution 3 will be great. Indeed JSON is easy to parse and it could be handled by another programs. I just hope that a JSON file will be understandable and readable for a human.

Is a Nagios user able to translate (just mentally) easily a such (pretty indented) JSON into nagios configuration?
If yes, the solution is clearly the best. 👍

**Comment by KenWhitesell** [comment]
I think it might be helpful with working on a solution #3-style approach if the alignak-backend-cli had an option to get an object with just the data fields that are necessary to create or update an object. (I'm primarily thinking of the livestate-related variables, "ls_*", although there may be others. Those change on a regular basis and could cause confusion when comparing versions.)

**Comment by mohierf** [comment]
Stand-by this for now ... Alignak is self sufficient with Nagios legacy configuration files as of now ! And it is possible to use the Shinken UI with this configuration

**Comment by mohierf** [comment]
Re-open to discuss this subject if needed!
