### ISSUE TITLE
Wrong permission on configuration file

### ISSUE THREAD

**Issue by hvad** [Alignak-monitoring/alignak#944]
Hi,

Ini and configuration files are marked as executable :

/etc/alignak/alignak.cfg                                                                                                                                  /etc/alignak/alignak.ini                                                                                                                                   /etc/alignak/daemons/arbiterd.ini                                                                                                                          /etc/alignak/daemons/brokerd.ini                                                                                                                           /etc/alignak/daemons/pollerd.ini                                                                                                                           /etc/alignak/daemons/reactionnerd.ini                                                                                                                      /etc/alignak/daemons/receiverd.ini                                                                                                                         /etc/alignak/daemons/schedulerd.ini                                                                                                                        /etc/alignak/daemons/reactionnerd.ini                                                                                                                      /etc/alignak/daemons/schedulerd.ini                                                                                                                        /etc/alignak/daemons/pollerd.ini                                                                                                                           /etc/alignak/daemons/brokerd.ini                                                                                                                           /etc/alignak/daemons/receiverd.ini          

Best regard

**Comment by mohierf** [comment]
Thanks @hvad. I will fix this rapidly
