### ISSUE TITLE
Cancel button in webui (edition mode) without effect 

### ISSUE THREAD

**Issue by Bastoune0604** [Alignak-monitoring/alignak#950]
# Cancel button in edition mode of the webui :

When you clic on the "Cancel button" in edition mode of the webui nothing arrived.
Not just for new host but all edition mode.

Screenshot : 
http://prntscr.com/h2rk2a

**Comment by mohierf** [comment]
You are right. The Cancel button is cleaning the form if you still entered some information in the input fields.

What behaviour did you expect? Going back to the former page in the history? Back to the home page?

**Comment by ddurieux** [comment]
Perhaps rename the button `clear` instead `cancel`

**Comment by Bastoune0604** [comment]
When i clic on Cancel button i think to "going back" but is not very usefull and  I am agree with ddurieux to rename the button "clear".

**Comment by mohierf** [comment]
I moved this issue to the WebUI repo, see https://github.com/Alignak-monitoring-contrib/alignak-webui/issues/347
