### ISSUE TITLE
Automatic comments text should be Alignak ...

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring/alignak#96]
... current default author for automatic generated comments is (Nagios process).

When a downtime is programmed an automatic comment is created. The author of this automatic comment is (Nagios Process) ... should use (Alignak) instead ?

What about having parameters in the configuration file for comments author and text ?

**Comment by ddurieux** [comment]
You're right to change author.

But don't think it must be configurable because it's automatic, so it's alignak do this
