### ISSUE TITLE
alignak on CentOS

### ISSUE THREAD

**Issue by trazomtg** [Alignak-monitoring/alignak#985]
hi,
when installing Alignak you can have this error:

    [root@Windows-Dell yumex]# pip  install alignak
    Collecting alignak
      Using cached alignak-1.0.0.tar.gz
        Complete output from command python setup.py egg_info:
       
        Installed /tmp/pip-build-8zCTxQ/alignak/pbr-1.0.0-py2.7.egg
        Marker evaluation failed, see the following error.  For more information see: http://docs.openstack.org/developer/pbr/compatibility.html#evaluate-marker
        ERROR:root:Error parsing
        Traceback (most recent call last):
          File "/tmp/pip-build-8zCTxQ/alignak/pbr-1.0.0-py2.7.egg/pbr/core.py", line 111, in pbr
            attrs = util.cfg_to_args(path, dist.script_args)
          File "/tmp/pip-build-8zCTxQ/alignak/pbr-1.0.0-py2.7.egg/pbr/util.py", line 251, in cfg_to_args
            kwargs = setup_cfg_to_setup_kwargs(config, script_args)
          File "/tmp/pip-build-8zCTxQ/alignak/pbr-1.0.0-py2.7.egg/pbr/util.py", line 434, in setup_cfg_to_setup_kwargs
            if pkg_resources.evaluate_marker('(%s)' % env_marker):
          File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1364, in evaluate_marker
            return interpret(parser.expr(text).totuple(1)[1])
          File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1342, in interpret
            return op(nodelist)
          File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1307, in atom
            return interpret(nodelist[2])
          File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1342, in interpret
            return op(nodelist)
          File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1324, in comparison
            raise SyntaxError(repr(cop)+" operator not allowed in environment markers")
        SyntaxError: '<' operator not allowed in environment markers
        Installing Alignak on Linux: linux2
       
        ========================================================================================================
        Alignak installable directories/files:
        will create directory: var/log/alignak
        will create directory: var/run/alignak
        will create directory: var/lib/alignak
        will create directory: var/libexec/alignak
        will copy:  etc/* to etc/alignak
        ========================================================================================================
       
        error in setup command: Error parsing /tmp/pip-build-8zCTxQ/alignak/setup.cfg: SyntaxError: '<' operator not allowed in environment markers
       
        ---------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8zCTxQ/alignak/

**i'ts a bad version of setuptools;  reinstall it**

**Comment by trazomtg** [comment]
il faut dans certains cas passer la commande 👍 
it's sometimes necessary to launch this command  👍 
 **python -m pip install --upgrade pip setuptools wheel**

**Comment by hvad** [comment]
Bonjour,

Vous pouvez installer le RPM du dépôt EPEL via la commande "yum install alignak-all" et installer la partie Alignak "core". 
Ensuite il vous faudra installer le backend et webui via pip pour l'instant.

Bonne journée

**Comment by mohierf** [comment]
Some information about this problem. This is because of an old pip version ... that does not accept using < > <= in the environment markers used in the the python requirement dependencies.
